#!/usr/bin/env python3
"""Regenerate the SYNTHETIC examples: result bundles and console text from the mock world, the example library, and the synthetic hub samples.

Everything written here comes from ``playqa.domain.mockworld`` (a fake place with planted faults), never from Studio. Files say so (a ``_synthetic`` field or this note).
Run after changing the generators, evaluators or the mock world, then ``python -m playqa eval run --label baseline``.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from playqa import project  # noqa: E402
from playqa.domain import baseline as B, checks as K, console as CON, gen, harness, judge, places, report as RP  # noqa: E402
from playqa.domain.mockworld import World  # noqa: E402

NOTE = "SYNTHETIC: generated by scripts/make_examples.py from the mock world (playqa/domain/mockworld.py); not captured from Roblox Studio."
P = project(ROOT)
PCTX = places.resolve(P, "demo_mine", "main")
LIB = K.load_library(ROOT)
PROBES = gen.load_probes(ROOT)
PATTERNS, CAUSES = CON.load_patterns(ROOT), RP.load_causes(ROOT)


def run_bundle(check_id: str, faults_by_run: list[list[str]], *, setup: dict | None = None) -> dict:
    c = LIB[check_id]
    results, consoles = [], []
    for i, faults in enumerate(faults_by_run, start=1):
        w = harness._world(faults, c, context=None, coins=None, test_mode=True, setup=setup, name=PCTX.entry.studio_name, place_id=0)
        phases = ["start", "end"] if c["kind"] == "perf" else [None]
        for ph in phases:
            s = gen.generate(c, PCTX.cfg, PCTX.style, PCTX.entry, PCTX.label, repeat_no=i, phase=ph, probes=PROBES)
            if ph == "end":
                w.advance(PCTX.cfg["performance"]["minutes"] * 60)
            results.append(w.run(s.luau))
        consoles.append(w.console_text())
    return {"_synthetic": NOTE, "place": "demo_mine/main", "check_id": check_id, "faults_by_run": faults_by_run, "setup": setup or {}, "results": results, "console_logs": consoles}


def judge_bundle(bundle: dict, baseline: dict | None = None):
    c = LIB[bundle["check_id"]]
    per = 2 if c["kind"] == "perf" else 1
    items = [{"result": r, "console_log": bundle["console_logs"][i // per]} for i, r in enumerate(bundle["results"])]
    return judge.judge(c, PCTX.cfg, PCTX.style, items, baseline=baseline, patterns=PATTERNS, causes=CAUSES)


def write(path: str, doc) -> None:
    f = ROOT / path
    f.parent.mkdir(parents=True, exist_ok=True)
    f.write_text(json.dumps(doc, indent=2, sort_keys=True) + "\n" if not isinstance(doc, str) else doc, encoding="utf-8")


CASES = [
    # name, check, faults per run, setup, polarity, title, description, tags
    ("boot-clean", "boot", [[]], None, "positive", "Clean boot", "The clean mock world passes boot: 4 of 4 services, 3 of 3 paths, no error or warning lines in the first 10 s.", ["boot", "clean"]),
    ("boot-error", "boot", [["boot_error"]], None, "negative", "Script error at boot", "AVOID: a boot script indexes nil at 1.2 s; the console and the LogService history both show one error line.", ["boot", "script-error"]),
    ("reach-unreachable-room", "reachability", [[]], None, "negative", "Unreachable room", "AVOID: spawn->Vault is NoPath while Shop and MineEntrance are reachable.", ["reachability", "unreachable"]),
    ("remotes-erroring", "remotes", [["remote_errors"]] * 3, None, "negative", "Remote that errors", "AVOID: BuyUpgrade's handler raises on a valid call and on every bad input, in 3 of 3 runs.", ["remotes", "error"]),
    ("economy-currency-bug", "economy_smoke", [["currency_bug"]] * 3, None, "negative", "Purchase that does not charge", "AVOID: buying PickaxeII leaves the balance at 15 (expected 5) in 3 of 3 runs.", ["economy", "currency"]),
    ("data-roundtrip-clean", "data_roundtrip", [[]], None, "positive", "Clean data round trip in test mode", "Saved markers 777 and 12 come back after reset and load; the switch was on and acknowledged.", ["data", "test-mode", "clean"]),
    ("perf-leak", "perf_snapshot", [[]] * 3, {"leak_mb_per_min": 20}, "negative", "Memory leak over a run", "AVOID: memory 410 -> 510 MB over 5 minutes is +24.39% (limit 20%).", ["performance", "leak"]),
]
FAULT_OVERRIDE = {"reach-unreachable-room": [["unreachable_room"]]}


def main() -> int:
    ps_base = harness.clean_baseline(P, PCTX)
    write("examples/baselines/default.json", {**ps_base, "_synthetic": NOTE})
    entries = []
    for name, cid, faults, setup, pol, title, desc, tags in CASES:
        bundle = run_bundle(cid, FAULT_OVERRIDE.get(name, faults), setup=setup)
        agg, rep = judge_bundle(bundle, baseline=ps_base if cid == "perf_snapshot" else None)
        write(f"examples/results/{name}.json", bundle)
        write(f"examples/consoles/{name}.txt", bundle["console_logs"][-1] + "\n")
        failed = sorted({f["assertion"] + (f"[{f['subject']}]" if f.get("subject") else "") for f in rep.get("failures", [])})
        dom = {"check_id": cid, "verdict": rep["verdict"], "failed_assertions": failed, "result_file": f"examples/results/{name}.json", "console_file": f"examples/consoles/{name}.txt"}
        if cid == "perf_snapshot":
            dom["baseline_name"] = "default"
        if rep.get("failures"):
            dom["measures"] = {"first_failure_measured": rep["failures"][0]["evidence"]["measured"]}
        entries.append({"id": f"qa-{name}", "kind": "failure_case" if pol == "negative" else "check_result", "title": title, "description": desc, "path": f"examples/results/{name}.json",
                        "application": {"name": "Roblox Studio", "version": "none (mock world, no Studio involved)"}, "license": {"owner": "user", "spdx": "MIT", "notes": NOTE},
                        "provenance": {"creator": "playqa example generator", "origin": "synthetic-example"}, "status": "curated", "polarity": pol, "rating": 5 if pol == "positive" else 1,
                        "tags": sorted(tags), "domain": dom, **({"correction_notes": [desc]} if pol == "negative" else {})})
    entries.append({"id": "qa-baseline-default", "kind": "baseline", "title": "Clean-world performance baseline", "description": "Part count 6, script count 3, memory 410 MB, frame 16.6 ms at the start and after 5 minutes on the clean mock world.",
                    "path": "examples/baselines/default.json", "application": {"name": "Roblox Studio", "version": "none (mock world, no Studio involved)"}, "license": {"owner": "user", "spdx": "MIT", "notes": NOTE},
                    "provenance": {"creator": "playqa example generator", "origin": "synthetic-example"}, "status": "curated", "polarity": "positive", "rating": 5, "tags": ["baseline", "performance"],
                    "domain": {"check_id": "perf_snapshot", "baseline_name": "default", "result_file": "examples/baselines/default.json"}})
    out = ROOT / "examples" / "library" / "assets.jsonl"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("".join(json.dumps(e, sort_keys=True) + "\n" for e in entries), encoding="utf-8")
    # --- synthetic hub samples (assumed shapes; see samples/README.md) ---
    boot = run_bundle("boot", [[]])
    write("samples/execute_luau/boot-clean.json", {"_synthetic": NOTE, "_assumed_shape": "a content list holding one text block with the script's returned string", "content": [{"type": "text", "text": boot["results"][0]}]})
    bad = run_bundle("boot", [["boot_error"]])
    write("samples/execute_luau/boot-error.json", {"_synthetic": NOTE, "_assumed_shape": "a bare JSON string returned by the script", "result": bad["results"][0]})
    write("samples/execute_luau/place-guard-refusal.json", {"_synthetic": NOTE, "_assumed_shape": "an error text from the hub when the script's place guard stops it", "isError": True,
                                                            "error": "wrong place: this script is for demo_mine/main (PlaceId 0) but PlaceId 5 is open"})
    write("samples/get_console_output/boot-error.txt", bad["console_logs"][0] + "\n")
    write("samples/get_console_output/boot-error-entries.json", {"_synthetic": NOTE, "_assumed_shape": "a list of {message, messageType, timestamp} entries (the LogService shape)",
                                                                  "entries": World(["boot_error"]).console_entries()})
    write("samples/list_roblox_studios/open-places.json", {"_synthetic": NOTE, "_assumed_shape": "a list of {name, place_id, studio_id}; the accepted key spellings are listed in guide_core.scope.match_open_studio",
                                                            "studios": [{"name": "Demo Mine Main (SYNTHETIC)", "place_id": 0, "studio_id": "studio-mine"}]})
    write("samples/screen_capture/README.txt", "SYNTHETIC. screen_capture returns an image; this tool never reads it. Save the image yourself (for example shots/s1.png) and pass the PATH to explain_failure as screenshots.\n")
    print(f"wrote {len(entries)} library entries, {len(CASES)} result bundles and the synthetic samples")
    return 0


if __name__ == "__main__":
    sys.exit(main())
