#!/usr/bin/env python3
"""Generate the synthetic example assets (GLB, glTF, OBJ, PNG, summary JSON, an FBX header stub) and examples/library/assets.jsonl.

Everything is built by script from preflight.domain.synth / fixtures: no external files, nothing downloaded. The files are synthetic test inputs,
not real Blender exports. Use --check to verify that the committed files equal what this script produces. Use --out DIR to write elsewhere.
"""
import argparse
import hashlib
import json
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from preflight.domain import engine, fixtures, loader, report  # noqa: E402

OUT = ROOT / "examples" / "assets"
LIBRARY = ROOT / "examples" / "library" / "assets.jsonl"
EDGE_CASES = {"sample_binary_header", "bad_draco_compressed", "bad_truncated", "good_summary_prop", "bad_summary_prop"}


def tree_hash(path: Path) -> dict[str, str]:
    return {str(p.relative_to(path)): hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(path.rglob("*")) if p.is_file()}


def entry(name: str, meta: dict, produced: Path, cfg) -> dict:
    expected, rules, tris = "error", [], None
    try:
        asset = loader.load_export(produced)
        rep = report.build_report(asset, cfg, meta["profile"])
        expected = rep["summary"]["result"]
        rules = sorted({f["rule"] for f in rep["findings"]})
        tris = rep["facts"]["triangles"]
    except ValueError:
        pass
    good = meta["kind"] == "good"
    kind = "export_case" if name in EDGE_CASES else ("good_export" if good else "bad_export")
    row = {"id": name.replace("_", "-"), "kind": kind, "title": name.replace("_", " "), "description": meta["summary"],
           "path": f"examples/assets/{produced.name}", "status": "curated", "polarity": "positive" if good else "negative",
           "license": {"owner": "user", "spdx": "MIT", "notes": "Synthetic example generated by scripts/make_examples.py"},
           "provenance": {"creator": "preflight example generator", "origin": "synthetic-example"},
           "application": {"name": "none (synthetic)", "version": "n/a"},
           "tags": sorted({meta["profile"], produced.suffix.lstrip("."), "synthetic", "good" if good else "bad"}),
           "domain": {"profile": meta["profile"], "format": produced.suffix.lstrip(".") if produced.suffix != ".json" else "summary", "expected_result": expected, "expected_rules": rules}}
    if tris is not None:
        row["domain"]["triangles"] = tris
    if not good:
        row["correction_notes"] = [f"{meta['summary']} Expected rules: {', '.join(rules) or 'a load error'}."]
    return row


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(OUT))
    ap.add_argument("--check", action="store_true", help="fail if the committed files differ from a fresh build")
    args = ap.parse_args()
    cfg = engine.load_config(ROOT)
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        produced = fixtures.build_all(tmp)
        rows = [entry(n, fixtures.CATALOG[n], produced[n], cfg) for n in fixtures.CATALOG]
        text = "".join(json.dumps(r, sort_keys=True, ensure_ascii=False) + "\n" for r in rows)
        if args.check:
            same = tree_hash(tmp) == tree_hash(Path(args.out)) and LIBRARY.exists() and LIBRARY.read_text(encoding="utf-8") == text
            print("examples are current" if same else "examples differ from a fresh build")
            return 0 if same else 1
        out = Path(args.out)
        out.mkdir(parents=True, exist_ok=True)
        for p in sorted(tmp.rglob("*")):
            if p.is_file():
                dest = out / p.relative_to(tmp)
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_bytes(p.read_bytes())
        LIBRARY.parent.mkdir(parents=True, exist_ok=True)
        LIBRARY.write_text(text, encoding="utf-8")
    print(f"wrote {len(fixtures.CATALOG)} assets to {out} and {LIBRARY}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
