#!/usr/bin/env python3
"""Regenerate the tracked SYNTHETIC examples: four hand-built toy economies, a sample import dump, plots and examples/library/assets.jsonl.

The toys are small enough to check on paper (the numbers are chosen so every purchase minute of the 'regular' archetype is an exact integer):

* balanced  - one ladder of 10 tiers, income doubles at each step (r_n = 10 * 2^n per minute for 'regular'), step cost = income x wanted minutes,
              a rebirth after tier 10, two boosts. Wanted minutes per tier: 10,10,10,20,30,40,60,80,100,120 (inside the placeholder bands).
* wall      - the same ladder, but tier 4 costs 32000 instead of 1600: a 400 minute wall.
* runaway   - three tiers that cost almost nothing against an income of 100/min: everything is bought in minutes and the currency floods.
* dominant  - the balanced ladder with tier 2 and tier 3 turned into choices where option A has the same cost and twice the income of option B.
"""
import copy
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from econbal import project  # noqa: E402
from guide_core.style import load_style  # noqa: E402
from econbal.domain import analysis as A, plot, rebalance as R, spec as S  # noqa: E402

P = project()
EX = P.root / "examples"
HEADER = "# SYNTHETIC toy economy generated by scripts/make_examples.py. Not a real game. See examples/positive and examples/negative.\n"
LIC = {"owner": "user", "spdx": "MIT", "notes": "Synthetic example generated by scripts/make_examples.py"}

WANTED_MINUTES = [10, 10, 10, 20, 30, 40, 60, 80, 100, 120]
ARCHETYPES = {
    "casual": {"session_minutes": 15, "sessions_per_day": 2, "efficiency": 0.8, "variance": 0.0, "boosts": []},
    "regular": {"session_minutes": 20, "sessions_per_day": 3, "efficiency": 1.0, "variance": 0.0, "boosts": []},
    "grinder": {"session_minutes": 60, "sessions_per_day": 4, "efficiency": 1.5, "variance": 0.0, "boosts": []},
}


def ladder(minutes=WANTED_MINUTES, base=10):
    """(cost, add) per tier: add = income before the step (income doubles), cost = income before x wanted minutes."""
    rows, rate = [], base
    for m in minutes:
        rows.append((rate * m, rate))
        rate *= 2
    return rows


def base_spec(sid: str, name: str, desc: str, rows, *, days=14, with_rebirth=True, boosts=True) -> dict:
    spec = {
        "format": S.FORMAT, "id": sid, "name": name, "description": desc,
        "simulation": {"days": days, "seed": 0, "policy": "cheapest_payback"},
        "currencies": {"coins": {"start": 0}},
        "sources": [{"id": "mining", "currency": "coins", "per_minute": 10}],
        "sinks": [],
        "upgrades": [{"id": f"drill_{i + 1}", "track": "drill", "tier": i + 1, "currency": "coins", "cost": c,
                      "effects": [{"source": "mining", "add": a}]} for i, (c, a) in enumerate(rows)],
        "boosts": ([{"id": "double_income", "kind": "gamepass", "price_robux": 399, "effects": [{"source": "*", "mult": 2}]},
                    {"id": "lucky_ore", "kind": "gamepass", "price_robux": 199, "effects": [{"source": "mining", "mult": 1.25}]}] if boosts else []),
        "archetypes": copy.deepcopy(ARCHETYPES),
        "rebirths": ([{"id": "rebirth", "currency": "coins", "cost": 1024000, "resets": {"tracks": ["drill"], "currencies": ["coins"]},
                       "bonus": {"source": "*", "mult_per_rebirth": 0.5}, "max": 2}] if with_rebirth else []),
        "locked": [],
    }
    return spec


def balanced() -> dict:
    s = base_spec("balanced", "Balanced toy economy", "One 10-tier ladder; regular players wait 10-120 active minutes per step; one rebirth loop; two boosts.", ladder())
    # tier 4 becomes a real choice whose options TRADE OFF: same payback (20 minutes), different cost and income.
    s["upgrades"][3]["strategy"] = "speed"
    s["upgrades"].insert(4, {"id": "drill_4b", "track": "drill", "tier": 4, "currency": "coins", "cost": 2400, "effects": [{"source": "mining", "add": 120}], "strategy": "value"})
    s["upgrades"][3]["name"] = "drill_4 (cheap)"
    s["upgrades"][4]["name"] = "drill_4b (dear)"
    return s


def wall() -> dict:
    rows = ladder()
    rows[3] = (32000, rows[3][1])  # tier 4 costs 20x more than the balanced 1600
    s = base_spec("wall", "Toy economy with a wall", "Same ladder as 'balanced', but drill_4 costs 32000: regular players wait 400 active minutes for it.", rows)
    return s


def runaway() -> dict:
    rows = [(100, 100), (300, 200), (900, 400)]
    s = base_spec("runaway", "Toy economy with runaway currency", "Income 100 per minute against costs of 100, 300 and 900: everything is bought in minutes and nothing is left to spend on.", rows, boosts=False,
                  with_rebirth=False)
    s["sources"][0]["per_minute"] = 100
    return s


def dominant() -> dict:
    rows = ladder()
    s = base_spec("dominant", "Toy economy with a dominant option", "The balanced ladder, but tiers 2 and 3 are choices where option A costs the same as B and gives twice the income.",
                  rows, boosts=False)
    ups = []
    for u in s["upgrades"]:
        if u["tier"] in (2, 3):
            a = copy.deepcopy(u)
            a["strategy"] = "speed"
            b = copy.deepcopy(u)
            b["id"] = u["id"] + "b"
            b["effects"] = [{"source": "mining", "add": u["effects"][0]["add"] / 2}]
            b["strategy"] = "value"
            ups += [a, b]
        else:
            ups.append(u)
    s["upgrades"] = ups
    return s


def write_yaml(name: str, spec: dict) -> Path:
    path = EX / "economies" / f"{name}.yaml"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(HEADER + S.dump_yaml(spec), encoding="utf-8")
    return path


def ctx_of(spec: dict) -> A.Ctx:
    errs = S.errors_of(S.validate(spec))
    assert not errs, errs
    return A.make_ctx(spec, load_style(P), A.load_rules(P.root))


SAMPLE_DUMP = {
    "format": "econbal-import/1", "game": "Sample Mine (hand-written)", "truncated": False,
    "currencies": [{"id": "Coins", "start": 0}],
    "containers": {
        "ores": {"path": "ReplicatedStorage.Ores", "items": [
            {"name": "Copper", "class": "Configuration", "fields": {"Value": 5, "ItemsPerMinute": 4, "Currency": "Coins"}},
            {"name": "Iron", "class": "Configuration", "fields": {"Value": 12, "ItemsPerMinute": 2, "Currency": "Coins"}}]},
        "tool_stats": {"path": "ReplicatedStorage.Tools", "items": [
            {"name": "StarterDrill", "class": "Configuration", "fields": {"Tier": 1, "SpeedMult": 1.0}},
            {"name": "SteelDrill", "class": "Configuration", "fields": {"Tier": 2, "SpeedMult": 1.5, "ValueMult": 1.0}},
            {"name": "DiamondDrill", "class": "Configuration", "fields": {"Tier": 3, "SpeedMult": 2.0, "ValueMult": 1.5}}]},
        "vendor_items": {"path": "ReplicatedStorage.Shop.Items", "items": [
            {"name": "Steel Drill", "class": "Configuration", "fields": {"Price": 200, "Tier": 2, "Category": "Drill", "Tool": "SteelDrill", "Currency": "Coins"}},
            {"name": "Diamond Drill", "class": "Configuration", "fields": {"Price": 1800, "Tier": 3, "Category": "Drill", "Tool": "DiamondDrill", "Currency": "Coins"}},
            {"name": "Iron Bonus", "class": "Configuration", "fields": {"Price": 120, "Tier": 1, "Category": "Drill", "Ore": "Iron", "Mult": 1.25}}]}}}


REGISTRY = """\
# SYNTHETIC registry of projects and places (generated by scripts/make_examples.py). Replace with your own games, or point ECONBAL_PROJECTS at your private file.
# Each place has ONE economy spec, ONE set of target pacing bands and ONE decision history (workspace/projects/<project_id>/<place_id>/).
projects:
  - project_id: demo_mine
    alias: Demo Mine (SYNTHETIC)
    universe_id: 0
    synthetic: true
    places:
      - {place_id: main, alias: Main mine, studio_name: "Demo Mine Main (SYNTHETIC)", roblox_place_id: 0, spec: projects/demo_mine/main/economy.yaml}
      - {place_id: hardcore, alias: Hardcore mode, studio_name: "Demo Mine Hardcore (SYNTHETIC)", roblox_place_id: 0, spec: projects/demo_mine/hardcore/economy.yaml, bands: projects/demo_mine/hardcore/bands.yaml}
  - project_id: demo_tycoon
    alias: Demo Tycoon (SYNTHETIC)
    universe_id: 9000000000
    synthetic: true
    places:
      - {place_id: main, alias: Tycoon, studio_name: "Demo Tycoon (SYNTHETIC)", roblox_place_id: 9000000001, spec: projects/demo_tycoon/main/economy.yaml}
"""

HARDCORE_BANDS = """\
# SYNTHETIC per-place bands for demo_mine/hardcore: slower pacing than the global placeholder bands. PLACEHOLDER numbers, not a real game's.
placeholder: true
name: Hardcore pacing bands (PLACEHOLDER)
target_bands:
  - {id: early, tiers: [1, 3],  min_minutes: 10, max_minutes: 30,  archetypes: [regular], placeholder: true}
  - {id: mid,   tiers: [4, 6],  min_minutes: 30, max_minutes: 90,  archetypes: [regular], placeholder: true}
  - {id: late,  tiers: [7, 99], min_minutes: 90, max_minutes: 240, archetypes: [regular], placeholder: true}
"""


def write_places(specs: dict) -> None:
    (P.root / "projects.yaml").write_text(REGISTRY, encoding="utf-8")
    for pid, plid, name in (("demo_mine", "main", "balanced"), ("demo_mine", "hardcore", "balanced"), ("demo_tycoon", "main", "runaway")):
        d = P.root / "projects" / pid / plid
        d.mkdir(parents=True, exist_ok=True)
        sp = copy.deepcopy(specs[name])
        sp["id"] = f"{pid}_{plid}"
        (d / "economy.yaml").write_text(HEADER.replace("toy economy", f"toy economy for the SYNTHETIC place {pid}/{plid}") + S.dump_yaml(sp), encoding="utf-8")
    (P.root / "projects" / "demo_mine" / "hardcore" / "bands.yaml").write_text(HARDCORE_BANDS, encoding="utf-8")


def main() -> None:
    specs = {"balanced": balanced(), "wall": wall(), "runaway": runaway(), "dominant": dominant()}
    ctxs, results = {}, {}
    for name, spec in specs.items():
        write_yaml(name, spec)
        ctxs[name] = ctx_of(spec)
        results[name] = A.check(ctxs[name])
    # a proposal for the wall, kept as an example of an accepted rebalance (generated by the tool, not by hand)
    base = results["wall"]
    target = R.select_finding(base["findings"], "wall", upgrade="drill_4", archetype="regular")
    prop = R.propose(ctxs["wall"], base, target, max_changes=1)
    assert prop["found"], prop
    fixed = R.apply_to_raw(specs["wall"], prop["changes"])
    fixed["id"] = "wall_rebalanced"
    fixed["name"] = "Toy economy with the wall fixed by propose_rebalance"
    write_yaml("wall_rebalanced", fixed)
    after = A.check(ctx_of(fixed))
    (EX / "imports").mkdir(parents=True, exist_ok=True)
    (EX / "imports" / "sample_dump.json").write_text(json.dumps(SAMPLE_DUMP, indent=2) + "\n", encoding="utf-8")
    (EX / "playtest").mkdir(parents=True, exist_ok=True)
    note = {"request": "Playtest note on the wall toy: tier 4 felt too slow", "decision": "revise", "reason": "tier 4 felt too slow",
            "corrections": [{"dimension": "pacing", "direction": "less", "felt": "too_slow", "tier": 4, "archetype": "regular", "note": "tier 4 felt too slow"}]}
    (EX / "playtest" / "tier4_felt_slow.json").write_text(json.dumps(note, indent=2) + "\n", encoding="utf-8")
    # projects and places (all SYNTHETIC): one registry, one folder per place
    write_places(specs)
    # plots
    for name in specs:
        plot.render(ctxs[name].sims(), EX / ("positive" if name == "balanced" else "negative") / f"{name}.png", title=f"{specs[name]['name']}")

    def codes(res, sev=("error", "warning")):
        return sorted({f["code"] for f in res["findings"] if f["severity"] in sev})

    def meas(res):
        m = res["metrics"]
        return {k: round(m[k], 3) for k in sorted(m)}

    rows = []

    def entry(eid, kind, title, path, polarity, desc, tags, domain, preview=None, notes=None, rating=None, status="curated", origin="synthetic-example"):
        row = {"id": eid, "kind": kind, "title": title, "path": path, "description": desc, "application": {"name": "Roblox Studio", "version": "none (no Studio involved)"},
               "license": LIC, "provenance": {"origin": origin, "creator": "econbal example generator"}, "tags": tags, "status": status, "polarity": polarity, "domain": domain}
        if preview:
            row["preview"] = preview
        if notes:
            row["correction_notes"] = notes
        if rating is not None:
            row["rating"] = rating
        return row

    dom = lambda name, res: {"spec_file": f"examples/economies/{name}.yaml", "expected_verdict": res["verdict"], "expected_codes": codes(res), "days": specs[name]["simulation"]["days"],
                              "seed": 0, "measurements": meas(res)}
    rows.append(entry("econ-balanced", "economy_spec", "Balanced toy economy", "examples/economies/balanced.yaml", "positive",
                      "Ten tiers whose regular-player steps (10,10,10,20,30,40,60,80,100,120 active minutes) sit inside the placeholder bands, a rebirth loop that keeps content from running out, a tie-break choice at tier 4, boosts under 3x. Passes every check.",
                      ["balanced", "ladder", "rebirth", "boosts"], dom("balanced", results["balanced"]), "examples/positive/balanced.png", rating=5))
    rows.append(entry("econ-wall", "economy_spec", "Toy economy with a wall (avoid)", "examples/economies/wall.yaml", "negative",
                      "AVOID: drill_4 costs 32000 against an income of 80 per minute, so regular players wait 400 active minutes. Flagged as wall, cost_cliff, gap_cliff.",
                      ["wall", "cost-cliff"], dom("wall", results["wall"]), "examples/negative/wall.png", notes=["wall: lower the cost of the step or add income before it", "cost: keep each step within 5x of the previous"]))
    rows.append(entry("econ-runaway", "economy_spec", "Toy economy with runaway currency (avoid)", "examples/economies/runaway.yaml", "negative",
                      "AVOID: income 100 per minute against costs 100, 300 and 900. Everything is bought within minutes and the currency floods. Flagged as under_band, content_exhausted, runaway_inflation.",
                      ["inflation", "runaway"], dom("runaway", results["runaway"]), "examples/negative/runaway.png", notes=["inflation: add sinks or content", "pacing: steps must take 5-15 minutes early on"]))
    rows.append(entry("econ-dominant", "economy_spec", "Toy economy with a dominant option (avoid)", "examples/economies/dominant.yaml", "negative",
                      "AVOID: at tiers 2 and 3 option A costs the same as option B and gives twice the income, so the choice is not a choice. Flagged as dominant_option, dominated_option, dominant_strategy.",
                      ["dominant", "choice"], dom("dominant", results["dominant"]), "examples/negative/dominant.png", notes=["dominant_option: make the alternatives trade off"]))
    rows.append(entry("rebalance-wall-001", "rebalance", "Wall fixed by a one-value change", "examples/economies/wall_rebalanced.yaml", "positive",
                      "propose_rebalance (max_changes=1) found the smallest change on its search grid that removes the wall at drill_4 without creating a new warning: "
                      + "; ".join(f"{c['path']} {c['before']} -> {c['after']}" for c in prop["changes"]) + ". Generated by the tool, not by hand.",
                      ["rebalance", "wall", "accepted"], {"spec_file": "examples/economies/wall_rebalanced.yaml", "expected_verdict": after["verdict"], "expected_codes": codes(after),
                                                           "days": 14, "seed": 0, "changes": [{"path": c["path"], "before": c["before"], "after": c["after"]} for c in prop["changes"]],
                                                           "measurements": meas(after)}, rating=4))
    rows.append(entry("playtest-tier4-slow", "playtest_note", "Playtest note: tier 4 felt too slow", "examples/playtest/tier4_felt_slow.json", "positive",
                      "A synthetic playtest note in the shape that suggest_band_adjustments reads: dimension pacing, tier 4, regular archetype, felt too_slow. Not a real playtest.",
                      ["playtest", "pacing"], {"seed": 0}))
    rows.append({"id": "econ-unreviewed-import", "kind": "economy_spec", "title": "Unreviewed import", "path": "examples/imports/sample_dump.json", "license": {"owner": "unknown"},
                 "provenance": {"origin": "user-supplied"}, "tags": ["import"], "status": "candidate", "polarity": "positive"})
    out = EX / "library" / "assets.jsonl"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(json.dumps(r, sort_keys=True) for r in rows) + "\n", encoding="utf-8")
    print(f"wrote {len(rows)} library entries")
    for n, r in results.items():
        print(n, r["verdict"], codes(r))
    print("wall fix:", prop["changes"])


if __name__ == "__main__":
    main()
