#!/usr/bin/env python3
"""Stamp the shared skeleton into a repository and vendor the shared core.

Usage:
    python suite/scaffold.py <repo-dir> --name substance-designer-ai --package sdai --prefix SDAI \
        --domain designer --kinds material,reference_image,graph_recipe --title "Substance 3D Designer AI Assistant"

Safe to re-run: files that carry domain content (README, AGENTS.md, skills, style, hooks, tools)
are never touched. Generated files are overwritten; the vendored core is replaced wholesale.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import textwrap
from pathlib import Path

SUITE = Path(__file__).resolve().parent
KIT = SUITE / "kit"

PYPROJECT = '''\
[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "{name}"
version = "0.1.0"
description = "{title}: instructions, tools, examples and evals that let a compatible AI agent do this work."
readme = "README.md"
requires-python = ">=3.10"
license = {{text = "MIT"}}
dependencies = ["mcp>=1.2", "pyyaml>=6", "jsonschema>=4.18"]

[project.optional-dependencies]
imaging = ["numpy>=1.24", "pillow>=10"]
embeddings = ["sentence-transformers>=2.7", "pillow>=10"]
dev = ["pytest>=7", "numpy>=1.24", "pillow>=10"{dev_extra}]
{extra_extras}
[project.scripts]
{name} = "{package}.__main__:main"
{name}-mcp = "{package}.server:main"

[tool.setuptools.packages.find]
include = ["{package}*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"
'''

GITIGNORE = '''\
# private, local data: your library, feedback, versions and generated output
workspace/
.env
*.egg-info/
__pycache__/
.pytest_cache/
.venv/
dist/
build/
# large binaries belong in your own asset store or Git LFS, not here
*.sbsar
*.hip
*.hiplc
*.rbxl
*.rbxlx
*.psd
'''

LICENSE = '''\
MIT License

Copyright (c) 2026 {name} contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
'''

ASSET_LICENSING = '''\
# Licensing of assets

The MIT license in `LICENSE` covers the **code, schemas and documentation** in this repository.

It does **not** grant any rights to assets you add. Your reference library is yours:

- Only ingest assets you made, or have permission to use as references. Record the owner in
  `license.owner` (`user`, `user-approved`, `third-party`). Entries with `unknown` owner stay
  `candidate` and are never returned by default searches.
- The files under `examples/` are **synthetic placeholders** generated by scripts in this repo
  so tests and demos run. They are released under the same MIT license and are not real
  production assets.
- Keep private or third-party assets outside Git (point `{prefix}_ASSET_ROOT` at them). This
  repository never uploads assets anywhere. If you use a hosted image or embedding service,
  check that service's terms for what happens to the data you send it.
- Fine-tuning a model on someone else's work may be restricted by their license. Check
  before building a training set.
'''

INIT = '''\
"""{title}."""

import os
from pathlib import Path

from .core.project import Project

KINDS = {kinds!r}


def project(root: str | Path | None = None) -> Project:
    """The repository context. Set {prefix}_ROOT to use a checkout from another working directory."""
    root = Path(root or os.environ.get("{prefix}_ROOT") or Path(__file__).resolve().parents[1])
    return Project(name="{name}", package="{package}", env_prefix="{prefix}", root=root,
                   domain="{domain}", asset_kinds=KINDS)
'''

MAIN = '''\
import sys

from . import project
from .core.cli import run
from .hooks import HOOKS


def main(argv=None) -> int:
    return run(project(), HOOKS, argv)


if __name__ == "__main__":
    sys.exit(main())
'''

SERVER = '''\
"""MCP server entry point: ``python -m {package}.server`` (stdio) or ``{name}-mcp``."""

import sys

from . import project
from .core.cli import all_tools
from .core.mcpkit import serve
from .hooks import HOOKS


def main(argv=None) -> int:
    transport = "stdio"
    args = list(sys.argv[1:] if argv is None else argv)
    if "--http" in args:
        transport = "streamable-http"
    p = project()
    serve(p, all_tools(p, HOOKS), HOOKS.instructions, transport)
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''

SYNC_SCRIPT = '''\
#!/usr/bin/env python3
"""Regenerate CLAUDE.md, GEMINI.md, .github/copilot-instructions.md and the skill mirrors.

Edit AGENTS.md and skills/ (the canonical sources), then run this. Use --check in CI.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from {package}.core.cli import run
from {package} import project
from {package}.hooks import HOOKS

sys.exit(run(project(), HOOKS, ["sync-agent-files", *sys.argv[1:]]))
'''

BUILD_SCHEMA = '''\
#!/usr/bin/env python3
"""Regenerate library/manifest.schema.json from the domain definition. Use --check in CI."""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from {package} import KINDS, project
from {package}.core.manifest import base_schema
from {package}.domain.schema import DOMAIN_SCHEMA

target = project().schema_file
text = json.dumps(base_schema(KINDS, DOMAIN_SCHEMA), indent=2) + "\\n"
if "--check" in sys.argv:
    sys.exit(0 if target.exists() and target.read_text(encoding="utf-8") == text else 1)
target.parent.mkdir(parents=True, exist_ok=True)
target.write_text(text, encoding="utf-8")
print(f"wrote {{target}}")
'''

CI = '''\
name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{{{ matrix.python-version }}}}
      - run: pip install -e ".[dev]"
      - run: python -m pytest
      - run: python -m {package} check-skills
      - run: python -m {package} sync-agent-files --check
      - run: python scripts/build_schema.py --check
      - run: python -m {package} eval run --label ci
'''

FEEDBACK_SCHEMA = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Feedback records written by core/feedback.py (one JSON object per line)",
    "$defs": {
        "run": {
            "type": "object",
            "required": ["run_id", "at", "request", "retrieved", "outputs"],
            "properties": {
                "run_id": {"type": "string", "pattern": "^run-[0-9]{8}-[0-9]{6}-[0-9a-f]{6}$"},
                "at": {"type": "string"},
                "request": {"type": "string", "minLength": 1},
                "constraints": {"type": "object"},
                "retrieved": {"type": "array", "items": {"type": "string"}},
                "tools": {"type": "array", "items": {"type": "string"}},
                "recipes": {"type": "array", "items": {"type": "string"}},
                "outputs": {"type": "array", "items": {"type": "string"}},
                "preview": {"type": ["string", "null"]},
                "model": {"type": ["string", "null"]},
                "extra": {"type": "object"},
            },
        },
        "decision": {
            "type": "object",
            "required": ["run_id", "at", "decision", "corrections"],
            "properties": {
                "run_id": {"type": "string"},
                "at": {"type": "string"},
                "decision": {"enum": ["accept", "reject", "revise"]},
                "reason": {"type": "string"},
                "corrections": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": ["dimension", "note"],
                        "properties": {"dimension": {"type": "string"}, "direction": {"enum": ["more", "less", "change"]},
                                       "note": {"type": "string"}},
                    },
                },
                "rating": {"type": ["integer", "null"], "minimum": 0, "maximum": 5},
                "promote_requested": {"type": "boolean"},
            },
        },
    },
}

FEEDBACK_README = '''\
# Feedback

Structured decisions are stored **locally** in `workspace/feedback/` (git-ignored):

- `runs.jsonl` - one record per task: request, constraints, retrieved reference IDs, tools and recipes
  used, output paths, preview.
- `decisions.jsonl` - the user's verdict (`accept`/`reject`/`revise`), reason, and structured corrections.

`schema.json` documents both record shapes. The implementation is `{package}/core/feedback.py`.

Nothing is learned automatically. Feedback changes future behaviour in three explicit ways:

1. `find_past_corrections` returns relevant old corrections so the agent reads them before planning.
2. `promote_run` (with `confirm=true`) can add a reviewed result to the example library. Unconfirmed
   promotion only creates a *candidate*, which default searches ignore.
3. Recurring corrections should be turned into style rules / recipe changes by a person or agent,
   plus an eval task that locks the lesson in.
'''


def adapter_files(name: str, package: str, prefix: str) -> dict[str, str]:
    """Example MCP client configs. Formats follow each client's documented shape; verify for your version."""
    env = {f"{prefix}_ROOT": "/ABSOLUTE/PATH/TO/" + name}
    std = {"mcpServers": {name: {"command": "python", "args": ["-m", f"{package}.server"], "env": env}}}
    vscode = {"servers": {name: {"type": "stdio", "command": "python", "args": ["-m", f"{package}.server"], "env": env}}}
    codex = (f'[mcp_servers.{name}]\ncommand = "python"\nargs = ["-m", "{package}.server"]\n'
             f'env = {{ {prefix}_ROOT = "/ABSOLUTE/PATH/TO/{name}" }}\n')
    readme = f"""\
# MCP client configuration examples

Replace `/ABSOLUTE/PATH/TO/{name}` with this checkout, and `python` with the interpreter of the
environment where you ran `pip install -e .` (a full path is safest, e.g. `.venv/bin/python`).

| Client | File | Where it goes |
|---|---|---|
| Claude Code | `claude-code.mcp.json` | project `.mcp.json`, or `claude mcp add {name} -e {prefix}_ROOT=/ABS/PATH -- python -m {package}.server` |
| Claude Desktop | `claude-desktop.json` | merge into `claude_desktop_config.json` |
| Cursor | `cursor.mcp.json` | `.cursor/mcp.json` |
| Gemini CLI | `gemini-settings.json` | merge `mcpServers` into Gemini's `settings.json` |
| VS Code / GitHub Copilot | `vscode.mcp.json` | `.vscode/mcp.json` |
| Codex CLI | `codex.config.toml` | merge into `~/.codex/config.toml` |

These follow each client's documented configuration shape but were **not** tested against live
clients while writing this repository. If a client rejects a file, check its current MCP docs: the
server itself is a standard stdio MCP server (`python -m {package}.server`).

The server speaks stdio and runs **locally**, as your user, with access to the directories in
`{prefix}_ALLOWED_PATHS` (default: `workspace/`). Do not expose it on a network: it has no authentication
(`--http` binds 127.0.0.1 only and refuses anything else).
"""
    return {
        "adapters/mcp-clients/claude-code.mcp.json": json.dumps(std, indent=2) + "\n",
        "adapters/mcp-clients/claude-desktop.json": json.dumps(std, indent=2) + "\n",
        "adapters/mcp-clients/cursor.mcp.json": json.dumps(std, indent=2) + "\n",
        "adapters/mcp-clients/gemini-settings.json": json.dumps(std, indent=2) + "\n",
        "adapters/mcp-clients/vscode.mcp.json": json.dumps(vscode, indent=2) + "\n",
        "adapters/mcp-clients/codex.config.toml": codex,
        "adapters/mcp-clients/README.md": readme,
    }


def ensure(path: Path, content: str, *, overwrite: bool) -> None:
    if path.exists() and not overwrite:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def vendor_core(repo: Path, package: str) -> None:
    dest = repo / package / "core"
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(KIT / "core", dest, ignore=shutil.ignore_patterns("__pycache__"))
    tests = repo / "tests" / "core_suite"
    if tests.exists():
        shutil.rmtree(tests)
    tests.mkdir(parents=True)
    for f in sorted((KIT / "tests").glob("*.py")):
        text = f.read_text(encoding="utf-8")
        text = re.sub(r"^from core(\.| )", rf"from {package}.core\1", text, flags=re.M)
        text = re.sub(r"^(\s+)from core(\.| )", rf"\1from {package}.core\2", text, flags=re.M)
        text = re.sub(r"^import core\b", f"import {package}.core as core", text, flags=re.M)
        if f.name == "conftest.py":  # the repo already has its package importable
            text = re.sub(r"HERE = .*?\n\nfrom core_support", "HERE = Path(__file__).resolve().parent\n\nfrom core_support",
                          text, flags=re.S)
            text = text.replace("for p in (HERE, HERE.parent):  # tests dir (core_support) and the kit dir (core)",
                                "for p in (HERE,):")
        (tests / f.name).write_text(text, encoding="utf-8")
    (tests / "README.md").write_text(
        f"These tests are vendored from the suite kit and exercise `{package}/core`. "
        "Do not edit them here; re-run `python suite/scaffold.py` from the workshop to refresh.\n", encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("repo")
    ap.add_argument("--name", required=True)
    ap.add_argument("--package", required=True)
    ap.add_argument("--prefix", required=True)
    ap.add_argument("--domain", required=True)
    ap.add_argument("--kinds", required=True)
    ap.add_argument("--title", required=True)
    ap.add_argument("--dev-deps", default="", help='extra dev dependencies, comma separated, e.g. "lupa>=2"')
    ap.add_argument("--extra", action="append", default=[], help='optional extra, e.g. "simulate=lupa>=2" (repeatable)')
    a = ap.parse_args()
    repo = Path(a.repo)
    kinds = tuple(k.strip() for k in a.kinds.split(","))
    dev_extra = "".join(f', "{d.strip()}"' for d in a.dev_deps.split(",") if d.strip())
    extra_extras = "".join(f'{e.split("=", 1)[0]} = ["{e.split("=", 1)[1]}"]\n' for e in a.extra)
    fmt = dict(name=a.name, package=a.package, prefix=a.prefix, domain=a.domain, kinds=kinds, title=a.title,
               dev_extra=dev_extra, extra_extras=extra_extras)

    ensure(repo / "pyproject.toml", PYPROJECT.format(**fmt), overwrite=True)
    ensure(repo / ".gitignore", GITIGNORE, overwrite=True)
    ensure(repo / "LICENSE", LICENSE.format(**fmt), overwrite=True)
    ensure(repo / "ASSET_LICENSING.md", ASSET_LICENSING.format(**fmt), overwrite=True)
    ensure(repo / a.package / "__init__.py", INIT.format(**fmt), overwrite=True)
    ensure(repo / a.package / "__main__.py", MAIN, overwrite=True)
    ensure(repo / a.package / "server.py", SERVER.format(**fmt), overwrite=True)
    ensure(repo / "scripts" / "sync_agent_files.py", SYNC_SCRIPT.format(**fmt), overwrite=True)
    ensure(repo / "scripts" / "build_schema.py", BUILD_SCHEMA.format(**fmt), overwrite=True)
    ensure(repo / ".github" / "workflows" / "ci.yml", CI.format(**fmt), overwrite=True)
    ensure(repo / "feedback" / "schema.json", json.dumps(FEEDBACK_SCHEMA, indent=2) + "\n", overwrite=True)
    ensure(repo / "feedback" / "README.md", FEEDBACK_README.format(**fmt), overwrite=True)
    for rel, text in adapter_files(a.name, a.package, a.prefix).items():
        ensure(repo / rel, text, overwrite=True)
    vendor_core(repo, a.package)
    print(f"scaffolded {repo}")


if __name__ == "__main__":
    main()
