"""Generated Luau: (1) a read-only dump of a game's economy tables to JSON, (2) a script that writes proposed values into a NEW config module.

Both are plain-Lua-compatible so the bundled mock (``mock_luau.py``, needs ``lupa``) can execute them. Neither publishes, saves, makes network
requests (except ``JSONEncode``), loads code, or overwrites/destroys anything. They are meant to be forwarded to Roblox Studio's own MCP
server (``execute_luau``) by the agent; this package never talks to Studio.
"""

from __future__ import annotations

import re
from typing import Any

from . import spec as S

ID_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_]{0,39}$")
SEGMENT_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_]{0,39}$")
VALUE_KEY_RE = re.compile(r"^[A-Za-z0-9_.]+$")
FORBIDDEN = ("Publish", "SavePlace", "MarketplaceService", "AssetService", "RequestAsync", "GetAsync", "PostAsync", "HttpService:Get", "HttpService:Post",
             "loadstring", "require(", "getfenv", "setfenv", "TeleportService", "DataStoreService", "MessagingService", "InsertService", "LoadAsset",
             ":Destroy(", "ClearAllChildren", "game:Destroy", "workspace:Destroy", "Parent = nil", "Parent=nil", "SaveInstance", "SavePlaceAsync")
MARKER = "econbal"

RESOLVE = [
    "local function resolveTarget(path)", "\tlocal parts = string.split(path, \".\")", "\tlocal node",
    '\tif string.lower(parts[1]) == "workspace" then', "\t\tnode = workspace", "\telse",
    "\t\tlocal ok, service = pcall(function() return game:GetService(parts[1]) end)",
    "\t\tif ok and service then node = service else node = game:FindFirstChild(parts[1]) end", "\tend",
    "\tfor i = 2, #parts do", "\t\tif not node then break end", "\t\tnode = node:FindFirstChild(parts[i])", "\tend",
    "\tif not node then error(\"path '\" .. path .. \"' was not found\") end", "\treturn node", "end", ""]


def place_guard(place_number: int, place_name: str, label: str) -> list[str]:
    """Luau lines that stop the script unless the open place is the named one (PlaceId when published, otherwise the place name)."""
    if not re.fullmatch(r"[A-Za-z0-9 _.()\-]{1,60}", place_name or ""):
        raise ValueError(f"place name {place_name!r} cannot be embedded safely")
    if not re.fullmatch(r"[A-Za-z0-9_/]{1,90}", label or ""):
        raise ValueError(f"place label {label!r} cannot be embedded safely")
    if not isinstance(place_number, int) or isinstance(place_number, bool) or place_number < 0:
        raise ValueError("place number must be a non-negative integer")
    return [f'local EXPECTED_PLACE_ID = {place_number}', f'local EXPECTED_NAME = "{place_name}"', f'local EXPECTED_LABEL = "{label}"',
            "if EXPECTED_PLACE_ID ~= 0 then", "	if game.PlaceId ~= EXPECTED_PLACE_ID then",
            "		error(\"wrong place: this script is for \" .. EXPECTED_LABEL .. \" (PlaceId \" .. EXPECTED_PLACE_ID .. \") but PlaceId \" .. tostring(game.PlaceId) .. \" is open\")",
            "	end", "elseif game.Name ~= EXPECTED_NAME then",
            "	error(\"wrong place: this script is for \" .. EXPECTED_LABEL .. \" (\" .. EXPECTED_NAME .. \") but \" .. tostring(game.Name) .. \" is open\")", "end", ""]


def validate_path(path: str, what: str = "path") -> str:
    parts = path.split(".")
    if not path or not all(SEGMENT_RE.match(p) for p in parts):
        raise ValueError(f"{what} '{path}' must be a dotted path of plain names such as ReplicatedStorage.Config (letters, digits, underscore)")
    return path


def validate_name(name: str, what: str = "config_name") -> str:
    if not ID_RE.match(name or ""):
        raise ValueError(f"{what} '{name}' must match {ID_RE.pattern}")
    return name


def lint(code: str) -> list[str]:
    issues = [f"forbidden token '{t}'" for t in FORBIDDEN if t in code]
    if "HttpService" in code:
        rest = code.replace('game:GetService("HttpService"):JSONEncode', "")
        if "HttpService" in rest.replace("-- ", ""):
            issues.append("HttpService may only be used for JSONEncode")
    return issues


def _num(v: float) -> str:
    if float(v) == int(v) and abs(v) < 1e15:
        return str(int(v))
    return repr(float(v))


def values_module_source(values: dict[str, float], *, spec_id: str, spec_hash: str, previous: dict[str, float] | None = None, label: str = "") -> str:
    """The Luau text of the proposed config module: a flat map from value path to number."""
    if label and not re.fullmatch(r"[A-Za-z0-9_/]{1,90}", label):
        raise ValueError(f"place label {label!r} cannot be embedded safely")
    for k in values:
        if not VALUE_KEY_RE.match(k):
            raise ValueError(f"value path '{k}' contains characters that are not allowed in generated Luau")
    if not ID_RE.match(spec_id):
        spec_id = re.sub(r"[^A-Za-z0-9_]", "_", spec_id) or "economy"
    lines = ["-- GENERATED by econbal - PROPOSED values for review. Not applied to the game until you wire them in.",
             f"-- spec {spec_id} {spec_hash}. Keys are value paths from economy.yaml.", "return {",
             f'\tmeta = {{spec_id = "{spec_id}", spec_hash = "{spec_hash}", place = "{label}", generated_by = "{MARKER}"}},', "\tvalues = {"]
    lines += [f'\t\t["{k}"] = {_num(v)},' for k, v in sorted(values.items())]
    lines.append("\t},")
    if previous is not None:
        lines.append("\tprevious = {")
        lines += [f'\t\t["{k}"] = {_num(v)},' for k, v in sorted(previous.items()) if k in values]
        lines.append("\t},")
    lines += ["}", ""]
    return "\n".join(lines)


def build_export_luau(module_source: str, *, parent_path: str, config_name: str, n_values: int, spec_hash: str, place: tuple[int, str, str]) -> str:
    validate_path(parent_path, "parent_path")
    validate_name(config_name)
    if "]==]" in module_source:
        raise ValueError("module source contains a Lua long-bracket terminator; refusing to embed it")
    code = "\n".join([
        f"-- GENERATED by econbal (spec {spec_hash}) - review before running.",
        f'-- Creates ONE NEW ModuleScript named {config_name} under {parent_path}. It never overwrites, replaces or deletes anything: if that name',
        "-- already exists it stops with an error. It does not publish, save, load code or make network requests.",
        f'local PARENT_PATH = "{parent_path}"', f'local MODULE_NAME = "{config_name}"', "", *place_guard(*place), *RESOLVE,
        "local parent = resolveTarget(PARENT_PATH)",
        "if parent:FindFirstChild(MODULE_NAME) then",
        "\terror(\"refusing to overwrite: '\" .. MODULE_NAME .. \"' already exists under \" .. PARENT_PATH .. \"; choose a new config_name\")",
        "end", "", "local SOURCE = [==[", module_source.rstrip("\n"), "]==]", "",
        'local module = Instance.new("ModuleScript")', "module.Name = MODULE_NAME", "module.Source = SOURCE",
        f'module:SetAttribute("AIGeneratedBy", "{MARKER}")', "module.Parent = parent", "",
        'local json = game:GetService("HttpService"):JSONEncode({status = "ok", path = module:GetFullName(), '
        f'values = {n_values}, spec_hash = "{spec_hash}"}})', "print(json)", "return json", ""])
    problems = lint(code)
    if problems:
        raise ValueError("generated Luau failed the safety lint: " + "; ".join(problems))
    return code


def build_import_luau(*, vendor_path: str | None = None, tools_path: str | None = None, ores_path: str | None = None, max_items: int = 500, place: tuple[int, str, str]) -> str:
    """Read-only Luau that dumps child Instances of up to three containers (attributes and Value objects) as JSON ``econbal-import/1``."""
    paths = {"vendor_items": vendor_path, "tool_stats": tools_path, "ores": ores_path}
    chosen = {k: validate_path(v, f"{k} path") for k, v in paths.items() if v}
    if not chosen:
        raise ValueError("give at least one of vendor_path, tools_path, ores_path (dotted paths such as ReplicatedStorage.Shop.Items)")
    if not isinstance(max_items, int) or not 1 <= max_items <= 5000:
        raise ValueError("max_items must be an integer from 1 to 5000")
    lines = ["-- GENERATED by econbal (import dump) - READ ONLY: it changes nothing, publishes nothing, makes no network requests.",
             "-- Prints and returns JSON in the econbal-import/1 format; give that JSON to normalise_import.", f"local MAX_ITEMS = {max_items}", "",
             "local TARGETS = {"]
    lines += [f'\t{{key = "{k}", path = "{v}"}},' for k, v in chosen.items()]
    lines += ["}", "", *place_guard(*place), *RESOLVE,
              "local function scalar(v)", "\tlocal t = type(v)", "\treturn t == \"number\" or t == \"string\" or t == \"boolean\"", "end", "",
              "local function readItem(inst)", "\tlocal fields = {}", "\tlocal attrs = inst:GetAttributes()", "\tfor k, v in pairs(attrs) do", "\t\tif scalar(v) then fields[k] = v end", "\tend",
              "\tif inst:IsA(\"ValueBase\") and scalar(inst.Value) then fields.Value = inst.Value end",
              "\tfor _, c in ipairs(inst:GetChildren()) do", "\t\tif c:IsA(\"ValueBase\") and scalar(c.Value) then fields[c.Name] = c.Value end", "\tend",
              "\treturn {name = inst.Name, class = inst.ClassName, fields = fields}", "end", "",
              "local containers = {}", "local truncated = false", "for _, target in ipairs(TARGETS) do", "\tlocal node = resolveTarget(target.path)", "\tlocal items = {}",
              "\tfor _, child in ipairs(node:GetChildren()) do", "\t\tif #items >= MAX_ITEMS then truncated = true break end", "\t\titems[#items + 1] = readItem(child)", "\tend",
              "\tcontainers[target.key] = {path = target.path, items = items}", "end", "",
              'local json = game:GetService("HttpService"):JSONEncode({format = "econbal-import/1", generated_by = "econbal", truncated = truncated, containers = containers})',
              "print(json)", "return json", ""]
    code = "\n".join(lines)
    problems = lint(code)
    if problems:
        raise ValueError("generated Luau failed the safety lint: " + "; ".join(problems))
    return code


def values_for_export(spec: dict, baseline: dict | None = None) -> tuple[dict[str, float], dict[str, float] | None]:
    """All numeric values of ``spec`` (tunable sections only), or only those that differ from ``baseline`` plus their previous values."""
    sections = ("currencies", "sources", "sinks", "upgrades", "boosts", "rebirths")
    cur = S.value_paths(spec, sections)
    if baseline is None:
        return cur, None
    old = S.value_paths(baseline, sections)
    changed = {p: v for p, v in cur.items() if old.get(p) != v}
    return changed, {p: old[p] for p in changed if p in old}


def verify_export_on_mock(code: str, module_source: str, values: dict[str, float], parent_path: str, config_name: str, *, pre_existing: bool = False,
                          open_place: tuple[str, int] | None = None) -> dict:
    """Run the generated script on the Luau mock and check what it created. Skips (does not fail) when ``lupa`` is not installed."""
    from . import mock_luau

    if mock_luau.LuaRuntime is None:
        return {"status": "skipped", "reason": "the optional 'lupa' package is not installed (pip install 'roblox-economy-balancer[simulate]')"}
    mock = mock_luau.MockRoblox()
    mock.ensure_path(parent_path)
    if open_place:
        mock.set_place(*open_place)
    if pre_existing:
        mock.add(parent_path, "ModuleScript", config_name)
    try:
        mock.run(code)
    except Exception as exc:  # a LuaError from the script is a result, not a crash
        return {"status": "error", "error": str(exc).splitlines()[0]}
    info = mock.info(f"{parent_path}.{config_name}")
    if info is None or info["class"] != "ModuleScript":
        return {"status": "error", "error": "the script did not create the ModuleScript"}
    if info["source"] != module_source:
        return {"status": "error", "error": "the created module's Source differs from the reviewed module text"}
    got = mock.lua.eval("function(src) local f = load(src) return f() end")(info["source"])
    bad = [k for k, v in values.items() if got["values"][k] != v]
    if bad:
        return {"status": "error", "error": f"module values differ from the spec for {bad[:3]}"}
    return {"status": "ok", "values_checked": len(values), "created": f"{parent_path}.{config_name}", "attributes": info["attributes"]}
