#!/usr/bin/env python3
"""Regenerate the tracked SYNTHETIC examples: images, briefs' measurements and examples/library/assets.jsonl.

The images are pipeline fixtures drawn by the placeholder renderer from a direction's palette and axes. They are NOT generated art and say nothing about
model quality. They exist so the retrieval, measurement and rubric code has deterministic positive and negative cases to exercise. Replace them with your own
curated concepts in your private library (CONCEPTAI_ASSET_ROOT).
"""
import json
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from conceptai import project  # noqa: E402
from conceptai.domain import analysis, direction as D, synthetic  # noqa: E402

P = project()
EX = P.root / "examples"
for sub in ("positive", "negative", "library"):
    (EX / sub).mkdir(parents=True, exist_ok=True)
LIC = {"owner": "user", "spdx": "MIT", "notes": "Synthetic fixture generated by scripts/make_examples.py"}
ENV = yaml.safe_load((EX / "briefs" / "lighthouse_env.yaml").read_text())
PROP = yaml.safe_load((EX / "briefs" / "lantern_prop.yaml").read_text())
SIZE = {"environment": (672, 384), "prop": (512, 512)}


def pick(brief, want):
    """The first direction (searching seeds) whose axes satisfy ``want`` - deterministic."""
    for seed in range(200):
        for d in D.generate_directions(brief, 6, seed)["directions"]:
            if all(d["axes"].get(k) == v for k, v in want.items()):
                return d
    raise SystemExit(f"no direction for {want}")


def meas(path, d, brief):
    box = (brief.get("locked", {}).get("composition") or {}).get("focal_box")
    m = analysis.measure(path, target_palette=[p["hex"] for p in d["palette"]] if d else (), focal_box=box)
    keep = ("value_range", "edge_density", "palette_adherence", "silhouette_components", "silhouette_fill", "saturation")
    return {k: round(float(m[k]), 4) for k in keep if k in m}


rows = []


def entry(eid, title, kind, polarity, rel, desc, tags, d, brief, notes=None, extra=None):
    row = {"id": eid, "kind": "concept", "title": title, "description": desc, "path": rel, "preview": rel, "license": LIC, "status": "curated", "polarity": polarity,
           "tags": sorted(set(tags)), "rating": 5 if polarity == "positive" else 1,
           "provenance": {"creator": "conceptai example generator", "origin": "synthetic-example"},
           "style": {"palette": [p["hex"] for p in d["palette"]] if d else [], "traits": list(d["axes"].values())[:4] if d else []},
           "domain": {"subject_kind": kind, "concept_only": True, "ai_generated": False, "synthetic_fixture": True, "axes": d["axes"] if d else {}, "measurements": meas(P.root / rel, d, brief)}}
    if notes:
        row["correction_notes"] = notes
    if extra:
        row["domain"].update(extra)
    rows.append(row)


# --- positives --------------------------------------------------------------------------------------------------------------------------
d_env = pick(ENV, {"lighting": "golden_hour", "palette_scheme": "analogous_warm"})
synthetic.save(synthetic.render(d_env, *SIZE["environment"], seed=1, label=False), EX / "positive" / "env_lighthouse_golden.png")
entry("env-lighthouse-golden-001", "Lighthouse at golden hour (fixture)", "environment", "positive", "examples/positive/env_lighthouse_golden.png",
      "Warm analogous palette, wide value range, a clear dark mass against a bright sky, accent colour at the focal point, one dominant silhouette. A FIXTURE for the measurement code: it shows the structure to aim for, not the quality of generated art.",
      ["lighthouse", "coast", "golden-hour", "environment", "readable"], d_env, ENV)
d_prop = pick(PROP, {"silhouette": "round_bulky", "palette_scheme": "complementary"})
synthetic.save(synthetic.render(d_prop, *SIZE["prop"], seed=2, label=False), EX / "positive" / "prop_lantern_round.png")
entry("prop-lantern-round-001", "Round lantern silhouette (fixture)", "prop", "positive", "examples/positive/prop_lantern_round.png",
      "One bulky silhouette that reads against the background, complementary palette with a single accent for the glass. A FIXTURE showing silhouette fill and palette adherence.",
      ["lantern", "prop", "silhouette", "readable"], d_prop, PROP)

# --- negatives --------------------------------------------------------------------------------------------------------------------------
synthetic.from_spec({"kind": "split", "left": "#7a7a78", "right": "#7f7f7d", "size": SIZE["environment"]}, EX / "negative" / "env_flat_low_contrast.png")
entry("env-flat-low-contrast-001", "Flat, low-contrast environment (fixture)", "environment", "negative", "examples/negative/env_flat_low_contrast.png",
      "Everything sits in one narrow value band: the focal point does not separate from the surround and the image does not read at thumbnail size.",
      ["environment", "flat", "low-contrast"], None, ENV, ["readability: widen the value range; make the focal point the lightest or darkest area", "lighting: add a clear light direction"])

d_other = pick(ENV, {"palette_scheme": "analogous_cool", "lighting": "overcast_soft"})
synthetic.save(synthetic.render(d_other, *SIZE["environment"], seed=3, label=False), EX / "negative" / "env_off_palette.png")
row_pal = [p["hex"] for p in d_env["palette"]]
analysis_m = analysis.measure(EX / "negative" / "env_off_palette.png", target_palette=row_pal)
entry("env-off-palette-001", "Cool overcast image for a warm golden-hour brief (fixture)", "environment", "negative", "examples/negative/env_off_palette.png",
      "Readable, but its dominant colours are far from the warm palette of the direction it was meant to follow: palette adherence is low.",
      ["environment", "off-palette"], d_other, ENV, ["palette: follow the direction's warm analogous palette"], {"intended_palette": row_pal, "palette_adherence_vs_intended": round(float(analysis_m["palette_adherence"]), 4)})

img = synthetic.render(d_env, *SIZE["environment"], seed=1, label=False)
from PIL import ImageDraw  # noqa: E402

ImageDraw.Draw(img).rectangle([8, 8, 36, 24], fill=(250, 250, 250))
synthetic.save(img, EX / "negative" / "env_near_duplicate.png")
entry("env-near-duplicate-001", "Near-duplicate of an existing concept (fixture)", "environment", "negative", "examples/negative/env_near_duplicate.png",
      "The same layout and palette as env-lighthouse-golden-001 with a tiny change. Presented as a new direction it would add nothing: novelty versus the library is near zero.",
      ["environment", "duplicate", "novelty"], d_env, ENV, ["novelty: change silhouette, lighting or composition, not a detail"])

synthetic.from_spec({"kind": "noise", "seed": 4, "size": SIZE["prop"], "base": "#808080"}, EX / "negative" / "prop_fragmented_noise.png")
entry("prop-fragmented-noise-001", "Noisy prop with no readable silhouette (fixture)", "prop", "negative", "examples/negative/prop_fragmented_noise.png",
      "Salt-and-pepper detail everywhere: the silhouette fragments into many pieces and no single form reads.",
      ["prop", "noise", "silhouette"], None, PROP, ["silhouette: one clear mass; group detail near one area", "detail_level: simplify"])

(EX / "library" / "assets.jsonl").write_text("\n".join(json.dumps(r, sort_keys=True) for r in rows) + "\n", encoding="utf-8")
print(f"wrote {len(rows)} entries")
for r in rows:
    print(r["id"], r["domain"]["measurements"])
