#!/usr/bin/env python3
"""Regenerate the tracked SYNTHETIC examples from scripts/example_fixtures.py.

Writes examples/negative|positive/*.luau (tabs for indentation), their READMEs, evals/tasks/{planted_bugs,known_gaps,clean_files}.yaml and
examples/library/assets.jsonl. Use --check to verify that the tracked files are up to date (used by a test).
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))

from example_fixtures import FIXTURES  # noqa: E402

LIC = {"owner": "user", "spdx": "MIT", "notes": "Synthetic example generated by scripts/make_examples.py"}


def tabs(code: str) -> str:
    return re.sub(r"^((?: {4})+)", lambda m: "\t" * (len(m.group(1)) // 4), code, flags=re.M)


def stem(f: dict) -> str:
    base = f["name"].rsplit(".luau", 1)[0]
    return re.sub(r"^gap[_-]", "", base) if f["gap"] else base


def task_id(f: dict) -> str:
    prefix = "gap" if f["gap"] else ("neg" if f["dir"] == "negative" else "pos")
    return f"{prefix}-" + re.sub(r"[^a-z0-9]+", "-", stem(f).lower()).strip("-")


def rel(f: dict) -> str:
    return f"examples/{f['dir']}/{f['folder'] or f['name']}"


def context_of(f: dict) -> str:
    n = f["name"] or ""
    return "server" if ".server." in n else "client" if ".client." in n else "module"


def render() -> dict[str, str]:
    out: dict[str, str] = {}
    for f in FIXTURES:
        if f["files"]:
            for fname, code in f["files"].items():
                out[f"examples/{f['dir']}/{f['folder']}/{fname}"] = tabs(code)
        else:
            out[rel(f)] = tabs(f["code"])
    # READMEs
    for d, title, intro, cols in (
        ("negative", "Negative examples (a bug is planted in each)",
         "Each file has one planted problem. The eval suite requires the review to report exactly the listed rule ids (as defects) and the listed question ids (low confidence). "
         "Rows marked KNOWN GAP are planted bugs the heuristic checker does NOT catch: they are counted against recall on purpose. All code is synthetic.",
         "| File | What is wrong | Defect rules | Questions | Mode |\n|---|---|---|---|---|"),
        ("positive", "Positive examples (clean, and false-positive traps)",
         "A correct review reports NOTHING for these files (zero defects and zero questions). Most are traps: code that looks like a bug to a naive text search. All code is synthetic.",
         "| File | Why it must stay clean | Mode |\n|---|---|---|")):
        rows = []
        for f in FIXTURES:
            if f["dir"] != d:
                continue
            nm = f"`{f['folder']}/`" if f["folder"] else f"`{f['name']}`"
            mode = "--strict" if f["strict"] else "default"
            if d == "negative":
                rows.append(f"| {nm} | {f['why']} | {', '.join(f['expect']) or '-'}{' (not caught)' if f['gap'] else ''} | {', '.join(f['questions']) or '-'} | {mode} |")
            else:
                rows.append(f"| {nm} | {f['why']} | {mode} |")
        extra = ""
        if d == "negative":
            extra = ("\n\nBackends (`luau-analyze`, `selene`, `stylua`) are not part of these expectations: the evals run the own-rule engine only, so they are deterministic on machines "
                     "with or without those tools.\n")
        out[f"examples/{d}/README.md"] = f"# {title}\n\n{intro}\n\n{cols}\n" + "\n".join(rows) + extra + "\n"
    # evals
    def make_task(f: dict) -> dict:
        folder = bool(f["folder"])
        inp = {"op": "review_folder" if folder else "review", ("folder" if folder else "file"): rel(f), "strict": f["strict"]}
        checks: list[dict] = []
        if f["dir"] == "negative" and not f["gap"]:
            checks += [{"type": "has_rule", "rule": r} for r in f["expect"]]
            checks += [{"type": "has_question", "rule": r} for r in f["questions"]]
            checks.append({"type": "precision_recall"})
        elif f["gap"]:
            checks.append({"type": "precision_recall", "allow_miss": True})
        else:
            checks += [{"type": "no_findings"}, {"type": "precision_recall"}]
        t = {"id": task_id(f), "title": f["why"], "expect_rules": f["expect"], "expect_questions": f["questions"]}
        if f["gap"]:
            t["known_gap"] = f["gap"]
        t.update({"input": inp, "checks": checks})
        return t

    groups = {"planted_bugs": [f for f in FIXTURES if f["dir"] == "negative" and not f["gap"]],
              "known_gaps": [f for f in FIXTURES if f["gap"]],
              "clean_files": [f for f in FIXTURES if f["dir"] == "positive"]}
    heads = {"planted_bugs": "# One planted bug per file: the review must report the expected rule id (and nothing else). Generated by scripts/make_examples.py from scripts/example_fixtures.py.\n",
             "known_gaps": "# Planted bugs the heuristics do NOT catch. They count against recall on purpose; allow_miss keeps the suite green while the gap is documented. Generated.\n",
             "clean_files": "# Clean files and false-positive traps: zero defects and zero questions. Generated by scripts/make_examples.py.\n"}
    for g, fx in groups.items():
        out[f"evals/tasks/{g}.yaml"] = heads[g] + yaml.safe_dump([make_task(f) for f in fx], sort_keys=False, width=200, allow_unicode=True)
    # library
    rows = []
    for f in FIXTURES:
        tags = sorted({"luau", f["dir"], *[r.rstrip("0123456789").lower() for r in f["expect"] + f["questions"]]})
        row = {"application": {"name": "Roblox Studio", "version": "unspecified (synthetic example)"},
               "description": f["why"], "domain": {"rule_ids": f["expect"], "question_rule_ids": f["questions"], "strict": f["strict"], "context": context_of(f)},
               "id": task_id(f).replace("neg-", "bad-").replace("pos-", "good-")[:63], "kind": "bad_script" if f["dir"] == "negative" else "good_script",
               "license": LIC, "path": rel(f), "polarity": "negative" if f["dir"] == "negative" else "positive",
               "provenance": {"creator": "luaurev example generator", "origin": "synthetic-example"}, "status": "curated",
               "tags": tags, "title": (f["name"] or f["folder"])}
        if f["gap"]:
            row["domain"]["known_gap"] = f["gap"]
        if f["dir"] == "negative":
            row["correction_notes"] = [f"planted: {f['why']}"]
        if f["dir"] == "positive":
            row["rating"] = 5
        rows.append(row)
    out["examples/library/assets.jsonl"] = "\n".join(json.dumps(r, sort_keys=True) for r in sorted(rows, key=lambda r: r["id"])) + "\n"
    return out


def main() -> int:
    files = render()
    if "--check" in sys.argv:
        stale = [p for p, text in files.items() if not (ROOT / p).exists() or (ROOT / p).read_text(encoding="utf-8") != text]
        print(json.dumps({"stale": stale}))
        return 1 if stale else 0
    for p, text in files.items():
        dest = ROOT / p
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(text, encoding="utf-8")
    print(f"wrote {len(files)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
