"""Generate self-contained Python scripts to run INSIDE Substance 3D Designer.

Why scripts instead of a live connection? Designer's Python API runs inside the application, and
this repository was written without a Designer installation to test a live plugin against. A
generated script is deterministic, reviewable before it runs (dry-run friendly) and works with any
agent that can write files. Each script writes a JSON result file that the tools here read back.

All three scripts (build / inspect / probe) are UNTESTED against a real Designer: the calls follow
Adobe's documented scripting API shape (``sd.getContext()``, ``SDGraph.newNode``,
``newPropertyConnectionFromId``, ``setInputPropertyValueFromId``, ``SDValue*.sNew``), but names and
signatures must be confirmed on your version. The *probe* script exists to do exactly that, and
every script reports API problems as readable errors in its result JSON instead of crashing silently.
"""

from __future__ import annotations

import hashlib
import json
from typing import Any

from .catalog import NodeSpec

HEADER = '''\
# GENERATED by sdai ({kind}). Review before running. Runs inside Substance 3D Designer's Python.
# Result is written to RESULT_PATH as JSON. Do not edit; regenerate from the recipe instead.
import json
import os
import traceback

RESULT_PATH = {result_path}
result = {{"status": "error", "errors": [], "warnings": []}}
'''

COMMON = '''\
def _finish():
    os.makedirs(os.path.dirname(RESULT_PATH) or ".", exist_ok=True)
    with open(RESULT_PATH, "w") as fh:
        json.dump(result, fh, indent=2, default=str)
    print("sdai: result written to", RESULT_PATH, "status:", result["status"])


def _norm(text):
    return "".join(c if c.isalnum() else "_" for c in str(text).lower()).strip("_")


def _library_resource(pkg_mgr, label):
    """Find a library graph whose identifier matches the label (case/space-insensitive)."""
    wanted = _norm(label)
    for package in pkg_mgr.getPackages():
        for res in package.getChildrenResources(True):
            try:
                if _norm(res.getIdentifier()) == wanted:
                    return res
            except Exception:
                continue
    return None
'''

BUILD_BODY = '''\
PLAN = json.loads(__PLAN_JSON__)
SAVE_PATH = __SAVE_PATH__
PLAN_HASH = __PLAN_HASH__
result.update({"graph": PLAN["graph_name"], "plan_hash": PLAN_HASH, "created_nodes": [], "connections": 0})


def to_sd_value(prop, value):
    from sd.api.sdvaluefloat import SDValueFloat
    from sd.api.sdvalueint import SDValueInt
    from sd.api.sdvaluebool import SDValueBool
    t = prop.getType()
    name = type(t).__name__
    if isinstance(value, dict) and "value" in value:
        value = value["value"]
    if name == "SDTypeFloat":
        return SDValueFloat.sNew(float(value))
    if name in ("SDTypeInt", "SDTypeInt32"):
        return SDValueInt.sNew(int(value))
    if name == "SDTypeBool":
        return SDValueBool.sNew(bool(value))
    if name == "SDTypeColorRGBA":
        from sd.api.sdbasetypes import ColorRGBA
        from sd.api.sdvaluecolorrgba import SDValueColorRGBA
        c = list(value) + [1.0] * (4 - len(value))
        return SDValueColorRGBA.sNew(ColorRGBA(c[0], c[1], c[2], c[3]))
    if name == "SDTypeEnum":
        from sd.api.sdvalueenum import SDValueEnum
        return SDValueEnum.sNew(t, int(value))
    raise RuntimeError("unsupported property type %s for '%s' (extend to_sd_value)" % (name, prop.getId()))


try:
    import sd
    from sd.api.sdbasetypes import float2
    from sd.api.sdproperty import SDPropertyCategory
    from sd.api.sdvaluestring import SDValueString
    from sd.api.sbs.sdsbscompgraph import SDSBSCompGraph

    app = sd.getContext().getSDApplication()
    pkg_mgr = app.getPackageMgr()
    package = pkg_mgr.newUserPackage()
    graph = SDSBSCompGraph.sNew(package)
    graph.setIdentifier(PLAN["graph_name"])

    nodes = {}
    for spec in PLAN["nodes"]:
        if spec["source"] == "atomic":
            node = graph.newNode(spec["definition"])
        else:
            res = _library_resource(pkg_mgr, spec["label"])
            if res is None:
                raise RuntimeError("library graph '%s' (node '%s') not found among loaded packages; "
                                   "load the Substance library or fix recipes/node_catalog.yaml"
                                   % (spec["label"], spec["id"]))
            node = graph.newInstanceNode(res)
        if node is None:
            raise RuntimeError("could not create node '%s' (%s)" % (spec["id"], spec["definition"] or spec["label"]))
        node.setPosition(float2(spec["x"], spec["y"]))
        nodes[spec["id"]] = node
        for pid, value in spec["params"].items():
            prop = node.getPropertyFromId(pid, SDPropertyCategory.Input)
            if prop is None:
                raise RuntimeError("node '%s' has no input property '%s'. Run the probe + catalog-diff." % (spec["id"], pid))
            node.setInputPropertyValueFromId(pid, to_sd_value(prop, value))
        result["created_nodes"].append(spec["id"])

    for c in PLAN["connections"]:
        src, dst = nodes[c["from_node"]], nodes[c["to_node"]]
        if src.newPropertyConnectionFromId(c["from_slot"], dst, c["to_slot"]) is None:
            raise RuntimeError("connection %s.%s -> %s.%s was rejected by Designer" %
                               (c["from_node"], c["from_slot"], c["to_node"], c["to_slot"]))
        result["connections"] += 1

    for o in PLAN["outputs"]:
        out = graph.newNode("sbs::compositing::output")
        out.setPosition(float2(o["x"], o["y"]))
        out.setAnnotationPropertyValueFromId("identifier", SDValueString.sNew(o["usage"]))
        if nodes[o["from_node"]].newPropertyConnectionFromId(o["from_slot"], out, "inputNodeOutput") is None:
            raise RuntimeError("could not connect output '%s'" % o["usage"])
        result["created_nodes"].append("output:" + o["usage"])
    result["warnings"].append("Output usages are identified by node identifier only; assign usage tags in Designer "
                              "if your export template needs them.")

    if SAVE_PATH:
        os.makedirs(os.path.dirname(SAVE_PATH) or ".", exist_ok=True)
        pkg_mgr.savePackageAs(package, SAVE_PATH)
        result["saved_to"] = SAVE_PATH
    result["status"] = "ok"
except Exception as exc:
    result["errors"].append("%s: %s" % (type(exc).__name__, exc))
    result["traceback"] = traceback.format_exc()
finally:
    _finish()
'''

INSPECT_BODY = '''\
try:
    import sd
    from sd.api.sdproperty import SDPropertyCategory

    app = sd.getContext().getSDApplication()
    graph = app.getQtForPythonUIMgr().getCurrentGraph()
    if graph is None:
        raise RuntimeError("no graph is open in the Designer graph view")
    nodes, edges = [], []
    for node in graph.getNodes():
        nid = node.getIdentifier()
        entry = {"id": nid, "definition": None, "params": {}}
        try:
            entry["definition"] = node.getDefinition().getId()
        except Exception as exc:
            result["warnings"].append("definition of %s: %s" % (nid, exc))
        for prop in node.getProperties(SDPropertyCategory.Input):
            try:
                value = node.getPropertyValue(prop)
                entry["params"][prop.getId()] = value.get() if hasattr(value, "get") else str(value)
            except Exception:
                pass
        nodes.append(entry)
        for prop in node.getProperties(SDPropertyCategory.Output):
            try:
                for conn in node.getPropertyConnections(prop):
                    edges.append({"from": nid, "from_slot": prop.getId(),
                                  "to": conn.getInputPropertyNode().getIdentifier(),
                                  "to_slot": conn.getInputProperty().getId()})
            except Exception as exc:
                result["warnings"].append("connections of %s.%s: %s" % (nid, prop.getId(), exc))
    result.update({"status": "ok", "graph": graph.getIdentifier(), "nodes": nodes, "connections": edges})
except Exception as exc:
    result["errors"].append("%s: %s" % (type(exc).__name__, exc))
    result["traceback"] = traceback.format_exc()
finally:
    _finish()
'''

PROBE_BODY = '''\
ATOMIC = __ATOMIC__
LIBRARY = __LIBRARY__
result.update({"atomic": {}, "library": {}, "api_surface": {}, "designer_version": None})

try:
    import sd
    from sd.api.sdproperty import SDPropertyCategory
    from sd.api.sbs.sdsbscompgraph import SDSBSCompGraph

    app = sd.getContext().getSDApplication()
    for getter in ("getVersion", "getApplicationVersion"):
        if hasattr(app, getter):
            result["designer_version"] = str(getattr(app, getter)())
            break
    pkg_mgr = app.getPackageMgr()
    package = pkg_mgr.newUserPackage()
    graph = SDSBSCompGraph.sNew(package)
    graph.setIdentifier("sdai_probe")

    result["api_surface"] = {
        "SDPackageMgr.newUserPackage": hasattr(pkg_mgr, "newUserPackage"),
        "SDPackageMgr.savePackageAs": hasattr(pkg_mgr, "savePackageAs"),
        "SDGraph.newNode": hasattr(graph, "newNode"),
        "SDGraph.newInstanceNode": hasattr(graph, "newInstanceNode"),
        "SDNode.newPropertyConnectionFromId": True,
        "app.getQtForPythonUIMgr": hasattr(app, "getQtForPythonUIMgr"),
    }

    def describe(node):
        info = {"inputs": [], "params": [], "outputs": [], "property_types": {}}
        for prop in node.getProperties(SDPropertyCategory.Input):
            tname = type(prop.getType()).__name__
            info["property_types"][prop.getId()] = tname
            (info["inputs"] if "Texture" in tname else info["params"]).append(prop.getId())
        for prop in node.getProperties(SDPropertyCategory.Output):
            info["outputs"].append(prop.getId())
            info["property_types"][prop.getId()] = type(prop.getType()).__name__
        return info

    for definition in ATOMIC:
        try:
            node = graph.newNode(definition)
            result["atomic"][definition] = describe(node) if node is not None else {"error": "newNode returned None"}
        except Exception as exc:
            result["atomic"][definition] = {"error": "%s: %s" % (type(exc).__name__, exc)}
    for label in LIBRARY:
        res = _library_resource(pkg_mgr, label)
        if res is None:
            result["library"][label] = None
            continue
        try:
            result["library"][label] = describe(graph.newInstanceNode(res))
        except Exception as exc:
            result["library"][label] = {"error": "%s: %s" % (type(exc).__name__, exc)}
    result["status"] = "ok"
except Exception as exc:
    result["errors"].append("%s: %s" % (type(exc).__name__, exc))
    result["traceback"] = traceback.format_exc()
finally:
    _finish()
'''


def plan_hash(plan: dict) -> str:
    return hashlib.sha256(json.dumps(plan, sort_keys=True).encode()).hexdigest()[:12]


def layout(plan: dict) -> dict:
    """Deterministic grid layout: x by dependency depth, y by order within the column."""
    depth: dict[str, int] = {}
    incoming: dict[str, list[str]] = {n["id"]: [] for n in plan["nodes"]}
    for c in plan["connections"]:
        incoming[c["to_node"]].append(c["from_node"])
    for n in plan["nodes"]:  # plan nodes are already topologically ordered
        depth[n["id"]] = 1 + max((depth[s] for s in incoming[n["id"]]), default=-1)
    columns: dict[int, int] = {}
    nodes = []
    for n in plan["nodes"]:
        d = depth[n["id"]]
        row = columns.get(d, 0)
        columns[d] = row + 1
        nodes.append({**n, "x": d * 192.0, "y": row * 144.0})
    out_x = (max(depth.values(), default=0) + 1) * 192.0
    outputs = [{**o, "x": out_x, "y": i * 144.0} for i, o in enumerate(plan["outputs"])]
    return {**plan, "nodes": nodes, "outputs": outputs}


def _fill(template: str, **values: str) -> str:
    for k, v in values.items():
        template = template.replace(f"__{k}__", v)
    return template


def build_create_script(plan: dict, result_path: str, save_path: str | None = None) -> str:
    laid = layout(plan)
    return (HEADER.format(kind="build graph", result_path=json.dumps(result_path)) + COMMON +
            _fill(BUILD_BODY, PLAN_JSON=repr(json.dumps(laid, sort_keys=True)), SAVE_PATH=repr(save_path),
                  PLAN_HASH=json.dumps(plan_hash(plan))))


def build_inspect_script(result_path: str) -> str:
    return HEADER.format(kind="inspect active graph", result_path=json.dumps(result_path)) + COMMON + INSPECT_BODY


def build_probe_script(catalog: dict[str, NodeSpec], result_path: str) -> str:
    atomic = sorted({s.definition for s in catalog.values() if s.source == "atomic"} | {"sbs::compositing::output"})
    library = sorted({s.label for s in catalog.values() if s.source == "library"})
    return (HEADER.format(kind="probe", result_path=json.dumps(result_path)) + COMMON +
            _fill(PROBE_BODY, ATOMIC=json.dumps(atomic), LIBRARY=json.dumps(library)))


def check_script_syntax(source: str) -> None:
    """Compile (not run) a generated script so syntax errors surface in tests/CI, not inside Designer."""
    compile(source, "<generated designer script>", "exec")
