#!/usr/bin/env python3
"""Regenerate the tracked SYNTHETIC examples: scenes, plan-view maps and examples/library/assets.jsonl.

The positive scene is built the way an agent should build one: locked hero pieces, a socket-snapped table group, then
seeded dressing. Negative scenes are the same room with deliberate defects. Measured fields come from the analysis.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from setdress import project  # noqa: E402
from setdress.domain import compose, dress, kit as K, mapview, scene as SC  # noqa: E402
from setdress.tools import load_kit  # noqa: E402

P = project()
KIT, _ = load_kit(P)
EX = P.root / "examples"
LIC = {"owner": "user", "spdx": "MIT", "notes": "Synthetic example generated by scripts/make_examples.py"}
(EX / "scenes").mkdir(parents=True, exist_ok=True)


def base_scene(sid: str) -> dict:
    return SC.normalize({
        "id": sid, "region": {"x": 0, "z": 0, "w": 40, "d": 30, "floor_y": 0},
        "exclusions": [[17, 0, 6, 3]],  # the front door
        "paths": [{"id": "entrance", "points": [[20, 3], [20, 14], [34, 14]], "width": 5}],
        "corridors": [{"id": "bar_view", "from": [20, 28], "to": [31, 5], "width": 2.5}],
        "focal": [{"id": "hearth", "at": [2, 15], "radius": 10, "min_priority": 4}, {"id": "bar", "at": [30, 3], "radius": 9, "min_priority": 4}],
        "instances": [
            {"id": "hearth_001", "module": "fireplace", "at": [2.0, 15.0], "yaw": 90.0, "scale": 1.0, "locked": True, "source": "user", "why": "locked hero piece"},
            {"id": "bar_001", "module": "bar_counter", "at": [30.0, 3.0], "yaw": 0.0, "scale": 1.0, "locked": True, "source": "user", "why": "locked hero piece"}],
        "grid": {"step": 1.0, "yaw_step": 90.0}})


def table_group(scene: dict) -> dict:
    t = dress.make_instance(scene, KIT, "table_round", (12, 20), iid="table_001", why="table group anchor")
    plan = {"adds": [t], "moves": [], "removes": []}
    s = SC.apply_plan(scene, plan)
    for name, target_socket, mod_socket in (("chair_front", "seat_front", "front"), ("chair_back", "seat_back", "front")):
        inst = dress.snap_to_socket(s, KIT, "table_001", target_socket, "chair", mod_socket, iid=name)
        s = SC.apply_plan(s, {"adds": [inst], "moves": [], "removes": []})
    lamp = dress.snap_to_socket(s, KIT, "table_001", "top", "lantern", "base", iid="lantern_001")
    s = SC.apply_plan(s, {"adds": [lamp], "moves": [], "removes": []})
    rug = dress.make_instance(s, KIT, "rug", (12, 20), iid="rug_001", why="under the table group")
    return SC.apply_plan(s, {"adds": [rug], "moves": [], "removes": []})


def dressed(scene: dict, seed: int, rules: dict) -> dict:
    res = dress.dress_region(scene, KIT, rules, seed)
    return SC.apply_plan(scene, res["plan"])


def entry(eid, title, scene, polarity, desc, tags, traits, notes=None, rating=None):
    scene = dict(scene)
    rel = f"examples/scenes/{scene['id']}.json"
    (P.root / rel).write_text(json.dumps(scene, indent=1, sort_keys=True) + "\n", encoding="utf-8")
    png = f"examples/{'positive' if polarity == 'positive' else 'negative'}/{scene['id']}.png"
    mapview.render(scene, KIT, P.root / png)
    m = compose.measure(scene, KIT)["metrics"]
    row = {"id": eid, "kind": "scene", "title": title, "path": rel, "preview": png, "source_file": "examples/kit/kit.yaml", "description": desc,
           "application": {"name": "Roblox Studio", "version": "unspecified (synthetic example)"}, "license": LIC,
           "provenance": {"origin": "synthetic-example", "creator": "setdress example generator"}, "tags": tags,
           "style": {"traits": traits, "composition": f"{len(scene['instances'])} items, coverage {m['coverage']}"}, "status": "curated", "polarity": polarity,
           "domain": {"scene_file": rel, "kit": "tavern_kit", "region_studs": [scene["region"]["w"], scene["region"]["d"]], "items": len(scene["instances"]),
                      "coverage": m["coverage"], "measurements": {k: m[k] for k in ("coverage", "max_module_share", "largest_free_rect_fraction", "collisions", "blocked_paths") if k in m}}}
    if rating is not None:
        row["rating"] = rating
    if notes:
        row["correction_notes"] = notes
    return row


rules = {"density": 0.2, "orient": "face_wall", "include_tags": ["furniture", "container", "decor", "structure", "storage"], "exclude_tags": ["wall", "light", "textile"],
         "weights": {"small": 2.0, "structure": 0.5}, "spacing": 1.0}
good = dressed(table_group(base_scene("tavern_corner")), 3, rules)
good["instances"] = [dict(i, source=i.get("source", "ai")) for i in good["instances"]]

hero_only = base_scene("tavern_bare")

repetitive = base_scene("tavern_all_barrels")
for n, (x, z) in enumerate([(8, 8), (12, 8), (8, 12), (12, 12), (8, 22), (12, 24), (26, 22), (30, 24), (34, 22), (26, 26), (34, 26), (30, 20)]):
    repetitive["instances"].append({"id": f"barrel_{n:03d}", "module": "barrel", "at": [float(x), float(z)], "y": 0.0, "yaw": 0.0, "scale": 1.0, "locked": False, "source": "ai", "why": ""})

blocked = table_group(base_scene("tavern_blocked_path"))
for n, (x, z) in enumerate([(20, 8), (20, 11), (26, 14)]):
    blocked["instances"].append({"id": f"crate_{n:03d}", "module": "crate_small", "at": [float(x), float(z)], "y": 0.0, "yaw": 0.0, "scale": 1.0, "locked": False, "source": "ai", "why": ""})
blocked["instances"].append({"id": "pillar_view", "module": "pillar", "at": [26.0, 16.0], "y": 0.0, "yaw": 0.0, "scale": 1.0, "locked": False, "source": "ai", "why": ""})

crowded = dressed(table_group(base_scene("tavern_crowded")), 5, {**rules, "density": 0.7, "spacing": 0.0, "max_items": 120, "max_attempts": 3000})

rows = [
    entry("tavern-corner-001", "Tavern corner, dressed", good, "positive",
          "Locked fireplace and bar as hero pieces, a socket-snapped table group (chairs, lantern, rug), then seeded dressing against the walls. Paths and the bar sightline stay clear, both focal points have a hero module, and there is an open rectangle in the middle.",
          ["tavern", "interior", "hero-pieces", "socket-snapping", "balanced"], ["focal-hierarchy", "grouping", "negative-space", "clear-paths"], rating=5),
    entry("tavern-bare", "Tavern corner, undressed (avoid)", hero_only, "negative",
          "AVOID: only the two hero pieces. Focal points are satisfied but coverage is far below the style range; the room reads empty.",
          ["tavern", "empty", "undressed"], ["too-empty"], notes=["density: add supporting furniture and small accents", "grouping: build a table group first"]),
    entry("tavern-all-barrels", "One prop everywhere (avoid)", repetitive, "negative",
          "AVOID: a dozen identical barrels. One module dominates the scene and neighbours repeat.", ["tavern", "repetition", "barrels"], ["monotone"],
          notes=["repetition: no module above 40% of the scene", "grouping: mix containers, furniture and decor"]),
    entry("tavern-blocked-path", "Path and sightline blocked (avoid)", blocked, "negative",
          "AVOID: crates sit on the entrance path and a pillar stands in the bar sightline. The room looks fine in a screenshot and plays badly.",
          ["tavern", "blocked-path", "sightline"], ["clearance"], notes=["clearance: keep functional paths 5 studs wide and eye-height sightlines open"]),
    entry("tavern-crowded", "Overcrowded (avoid)", crowded, "negative",
          "AVOID: coverage far above the style range. Everything is placed, nothing breathes, and there is no open area to read the space.",
          ["tavern", "crowded", "density"], ["overcrowded"], notes=["density: fewer, better-placed pieces", "negative_space: keep a large open rectangle"]),
]
rows.append({"id": "scene-unreviewed-import", "kind": "scene", "title": "Unreviewed scene import", "path": "examples/scenes/tavern_corner.json",
             "license": {"owner": "unknown"}, "provenance": {"origin": "user-supplied"}, "tags": ["tavern"], "status": "candidate", "polarity": "positive"})
out = EX / "library" / "assets.jsonl"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("\n".join(json.dumps(r, sort_keys=True) for r in rows) + "\n", encoding="utf-8")
print(f"wrote {len(rows)} entries")
