"""Generate Luau for Roblox Studio from effect plans, plus a safety lint.

The generated code is plain Luau (no type annotations or newer syntax) so it can also be syntax-checked
and executed against a mock environment in tests. It is meant to be run with Studio's built-in MCP tool
``execute_luau`` (Edit datamodel) or pasted into the command bar.

Safety properties, enforced by ``lint`` and tests:
* it creates ONE root named ``AIEffect_<name>`` and replaces only a previous root carrying the attribute
  ``AIGeneratedBy == "rbxvfx"``; anything else with that name makes it stop with an error;
* it never publishes, saves, makes HTTP requests, or loads code (HttpService is used only for JSONEncode).
"""

from __future__ import annotations

import json
import re

from . import api, effects

MARKER = "rbxvfx"
FORBIDDEN = ("Publish", "SavePlace", "SaveToRoblox", "MarketplaceService", "AssetService", "RequestAsync",
             "HttpService:Get", "HttpService:Post", "loadstring", "require(", "getfenv", "setfenv", "TeleportService",
             "DataStoreService", "MessagingService", "ClearAllChildren", "game:Destroy", "workspace:Destroy")

HEADER = """\
-- GENERATED by rbxvfx (plan {hash}) - review before running.
-- Creates/replaces ONE effect root. It only ever replaces a root it created itself (attribute AIGeneratedBy = "{marker}").
-- It does not publish, save, or make network requests.
"""

RESOLVE = """\
local function resolveTarget(path)
	local parts = string.split(path, ".")
	local node
	if string.lower(parts[1]) == "workspace" then
		node = workspace
	else
		local ok, service = pcall(function() return game:GetService(parts[1]) end)
		if ok and service then node = service else node = game:FindFirstChild(parts[1]) end
	end
	for i = 2, #parts do
		if not node then break end
		node = node:FindFirstChild(parts[i])
	end
	if not node then error("target path '" .. path .. "' was not found") end
	return node
end
"""

SER = """\
local function ser(v)
	local t = typeof(v)
	if t == "number" or t == "boolean" or t == "string" then return v end
	if t == "NumberRange" then return {t = "NumberRange", min = v.Min, max = v.Max} end
	if t == "NumberSequence" then
		local keys = {}
		for _, kp in ipairs(v.Keypoints) do table.insert(keys, {kp.Time, kp.Value, kp.Envelope}) end
		return {t = "NumberSequence", keys = keys}
	end
	if t == "ColorSequence" then
		local keys = {}
		for _, kp in ipairs(v.Keypoints) do table.insert(keys, {kp.Time, {kp.Value.R, kp.Value.G, kp.Value.B}}) end
		return {t = "ColorSequence", keys = keys}
	end
	if t == "Color3" then return {t = "Color3", rgb = {v.R, v.G, v.B}} end
	if t == "Vector2" then return {t = "Vector2", v = {v.X, v.Y}} end
	if t == "Vector3" then return {t = "Vector3", v = {v.X, v.Y, v.Z}} end
	if t == "EnumItem" then return {t = "Enum", enum = tostring(v.EnumType), name = v.Name} end
	if t == "Instance" then return {t = "Ref", name = v.Name} end
	return nil
end
"""


def num(x: float) -> str:
    if float(x) == int(x) and abs(x) < 1e9:
        return str(int(x))
    return f"{x:.6g}"


def string(s: str) -> str:
    if not re.fullmatch(r"[\x20-\x7e]*", s):
        raise ValueError(f"only printable ASCII is allowed in generated strings (got {s!r})")
    return json.dumps(s)


def value(ir) -> str:
    if isinstance(ir, bool):
        return "true" if ir else "false"
    if isinstance(ir, (int, float)):
        return num(ir)
    if isinstance(ir, str):
        return string(ir)
    t = ir["t"]
    if t == "NumberRange":
        return f"NumberRange.new({num(ir['min'])}, {num(ir['max'])})"
    if t == "NumberSequence":
        keys = ", ".join(f"NumberSequenceKeypoint.new({num(k[0])}, {num(k[1])}, {num(k[2])})" for k in ir["keys"])
        return f"NumberSequence.new({{{keys}}})"
    if t == "ColorSequence":
        keys = ", ".join(f"ColorSequenceKeypoint.new({num(k[0])}, Color3.new({', '.join(num(c) for c in k[1])}))" for k in ir["keys"])
        return f"ColorSequence.new({{{keys}}})"
    if t == "Color3":
        return f"Color3.new({', '.join(num(c) for c in ir['rgb'])})"
    if t in ("Vector2", "Vector3"):
        return f"{t}.new({', '.join(num(c) for c in ir['v'])})"
    if t == "Enum":
        return f"Enum.{ir['enum']}.{ir['name']}"
    raise ValueError(f"cannot encode {ir!r}")


def _ident(instance_id: str) -> str:
    return "inst_" + re.sub(r"[^A-Za-z0-9_]", "_", instance_id)


def _order(plan: dict) -> list[dict]:
    """Parents before children, Attachments before the Beams/Trails that reference them."""
    done: list[dict] = []
    seen: set[str] = {"root"}
    pending = list(plan["instances"])
    while pending:
        progressed = False
        for inst in list(pending):
            needs = [inst["parent"]] + list(inst["refs"].values())
            if all(n in seen for n in needs):
                done.append(inst)
                seen.add(inst["id"])
                pending.remove(inst)
                progressed = True
        if not progressed:
            raise ValueError("instance tree has a cycle or an unknown parent/reference")
    return done


TARGET_RE = re.compile(r"[A-Za-z0-9_]+(\.[A-Za-z0-9_ ]+)*")


def validate_target_path(path: str) -> str:
    """Dotted DataModel path such as ``workspace.Effects``. Anything else could break out of the Luau string."""
    if not TARGET_RE.fullmatch(path):
        raise ValueError(f"target path '{path}' must be a dotted path like workspace.Effects")
    return path


def build_create_script(plan: dict, target_path: str = "workspace", position: tuple = (0, 5, 0), *,
                        emit_now: bool = False) -> str:
    """Luau that builds the effect under ``target_path``. ``emit_now`` fires burst emitters once."""
    problems = [f for f in effects.validate_plan(plan) if f["severity"] == "error"]
    if problems:
        raise ValueError("refusing to generate Luau for an invalid plan: " + problems[0]["message"])
    validate_target_path(target_path)
    out = [HEADER.format(hash=effects.plan_hash(plan), marker=MARKER),
           f"local TARGET_PATH = {string(target_path)}",
           f"local ROOT_NAME = {string(plan['root_name'])}",
           f"local POSITION = Vector3.new({', '.join(num(p) for p in position)})",
           f"local EMIT_NOW = {'true' if emit_now else 'false'}",
           "", RESOLVE, "local target = resolveTarget(TARGET_PATH)",
           "local existing = target:FindFirstChild(ROOT_NAME)",
           "if existing then",
           f'\tif existing:GetAttribute("AIGeneratedBy") == "{MARKER}" then',
           "\t\texisting:Destroy()",
           "\telse",
           "\t\terror(\"refusing to replace '\" .. ROOT_NAME .. \"': it was not created by rbxvfx\")",
           "\tend", "end", ""]
    if plan["mount"] == "part":
        out += ['local root = Instance.new("Part")', "root.Name = ROOT_NAME", "root.Anchored = true",
                "root.CanCollide = false", "root.CanQuery = false", "root.CanTouch = false",
                "root.Transparency = 1", "root.Size = Vector3.new(0.2, 0.2, 0.2)", "root.Position = POSITION"]
    else:
        out += ['if not target:IsA("BasePart") and not target:IsA("Attachment") then',
                '\terror("mount = attachment needs the target to be a BasePart or Attachment")', "end",
                'local root = Instance.new("Attachment")', "root.Name = ROOT_NAME"]
    out += [f'root:SetAttribute("AIGeneratedBy", "{MARKER}")', f'root:SetAttribute("AIEffect", {string(plan["name"])})',
            f'root:SetAttribute("AIPlanHash", {string(effects.plan_hash(plan))})', ""]
    for inst in _order(plan):
        v = _ident(inst["id"])
        out.append(f'local {v} = Instance.new("{inst["class"]}")')
        out.append(f"{v}.Name = {string(inst['name'])}")
        for pname in sorted(inst["properties"]):
            out.append(f"{v}.{pname} = {value(inst['properties'][pname])}")
        for pname in sorted(inst["refs"]):
            out.append(f"{v}.{pname} = {_ident(inst['refs'][pname])}")
        parent = "root" if inst["parent"] == "root" else _ident(inst["parent"])
        out.append(f"{v}.Parent = {parent}")
        out.append("")
    out += ["root.Parent = target", 'game:GetService("CollectionService"):AddTag(root, "AIEffect")', "",
            "if EMIT_NOW then"]
    for iid, count in sorted(plan["emit"].items()):
        out.append(f"\t{_ident(iid)}:Emit({count})")
    out += ["end", "", "local created = {}", "for _, d in ipairs(root:GetDescendants()) do",
            "\ttable.insert(created, {name = d.Name, class = d.ClassName, path = d:GetFullName()})", "end",
            'local json = game:GetService("HttpService"):JSONEncode({status = "ok", root = root:GetFullName(), '
            f'plan_hash = {string(effects.plan_hash(plan))}, created = created}})',
            "print(json)", "return json", ""]
    code = "\n".join(out)
    issues = lint(code)
    if issues:
        raise ValueError("generated Luau failed the safety lint: " + "; ".join(issues))
    return code


def build_remove_script(root_name: str, target_path: str = "workspace") -> str:
    code = "\n".join([HEADER.format(hash="remove", marker=MARKER), f"local TARGET_PATH = {string(target_path)}",
                      f"local ROOT_NAME = {string(root_name)}", "", RESOLVE, "local target = resolveTarget(TARGET_PATH)",
                      "local existing = target:FindFirstChild(ROOT_NAME)", "local status = \"not_found\"",
                      "if existing then", f'\tif existing:GetAttribute("AIGeneratedBy") == "{MARKER}" then',
                      "\t\texisting:Destroy()", "\t\tstatus = \"removed\"", "\telse",
                      "\t\terror(\"refusing to remove '\" .. ROOT_NAME .. \"': it was not created by rbxvfx\")", "\tend", "end",
                      'local json = game:GetService("HttpService"):JSONEncode({status = status})', "print(json)", "return json", ""])
    issues = lint(code)
    if issues:
        raise ValueError("generated Luau failed the safety lint: " + "; ".join(issues))
    return code


def inspectable_properties(cls: str) -> list[str]:
    snap = api.load()
    skip = {"Parent", "Archivable", "TextureContent", "WorldAxis", "WorldCFrame", "WorldOrientation", "WorldPosition",
            "WorldRotation", "WorldSecondaryAxis", "CFrame", "LocalTransparencyModifier"}
    out = []
    for name, info in sorted(api.properties(cls, snap).items()):
        if name in skip or info["deprecated"]:
            continue
        if info["type"] in api.SUPPORTED_TYPES or api.enum_values(info["type"], snap) is not None:
            out.append(name)
    return out


def build_inspect_script(path: str) -> str:
    """Luau that serialises every supported effect instance under ``path`` to JSON (printed and returned)."""
    validate_target_path(path)
    classes = ", ".join(f"[{string(c)}] = {{{', '.join(string(p) for p in inspectable_properties(c))}}}"
                        for c in api.ALLOWED_CLASSES)
    code = "\n".join([f"-- GENERATED by rbxvfx (inspect) - read-only: reads properties, changes nothing.",
                      f"local ROOT_PATH = {string(path)}", f"local CLASS_PROPS = {{{classes}}}", "", RESOLVE, SER,
                      "local root = resolveTarget(ROOT_PATH)", "local out = {}",
                      "local function visit(inst, parentName)",
                      "\tlocal props = CLASS_PROPS[inst.ClassName]",
                      "\tif props then",
                      "\t\tlocal row = {class = inst.ClassName, name = inst.Name, parent = parentName, properties = {}}",
                      "\t\tfor _, p in ipairs(props) do",
                      "\t\t\tlocal ok, v = pcall(function() return inst[p] end)",
                      "\t\t\tif ok then local s = ser(v); if s ~= nil then row.properties[p] = s end end",
                      "\t\tend",
                      "\t\ttable.insert(out, row)",
                      "\tend",
                      "\tfor _, child in ipairs(inst:GetChildren()) do visit(child, inst.Name) end",
                      "end",
                      "visit(root, \"\")",
                      'local json = game:GetService("HttpService"):JSONEncode({status = "ok", root = root.Name, instances = out})',
                      "print(json)", "return json", ""])
    issues = lint(code)
    if issues:
        raise ValueError("generated Luau failed the safety lint: " + "; ".join(issues))
    return code


def lint(code: str) -> list[str]:
    """Static safety checks on generated (or user-supplied) Luau. Returns a list of problems."""
    issues = [f"forbidden token '{tok}'" for tok in FORBIDDEN if tok in code]
    for m in re.finditer(r":Destroy\(\)", code):
        window = code[max(0, m.start() - 160) : m.start()]
        if f'GetAttribute("AIGeneratedBy") == "{MARKER}"' not in window:
            issues.append("Destroy() is not directly guarded by the AIGeneratedBy check")
    if re.search(r"HttpService", code) and not re.search(r'GetService\("HttpService"\):JSONEncode', code):
        issues.append("HttpService may only be used for JSONEncode")
    return issues


def parse_inspection(data: dict) -> dict:
    """Turn the JSON from ``build_inspect_script`` into a plan-shaped dict for ``effects.validate_plan``."""
    rows = data["instances"]
    root_name = data["root"]
    ids: dict[str, str] = {}
    instances = []
    for row in rows:
        if row["name"] == root_name and row["parent"] == "":
            continue  # the (Part/Attachment) root is not an authored instance
        iid = row["name"]
        ids[row["name"]] = iid
    for row in rows:
        if row["name"] == root_name and row["parent"] == "":
            continue
        parent = "root" if row["parent"] == root_name else row["parent"]
        props, refs = {}, {}
        for k, v in row["properties"].items():
            if isinstance(v, dict) and v.get("t") == "Ref":
                refs[k] = v["name"]
            else:
                props[k] = v
        instances.append({"id": row["name"], "class": row["class"], "parent": parent, "name": row["name"],
                          "properties": props, "refs": refs})
    kind = "loop"
    plan = {"recipe": "(inspected)", "name": re.sub(r"^AIEffect_", "", root_name), "root_name": root_name, "kind": kind,
            "mount": "part", "parameters": {}, "instances": instances, "emit": {}}
    if not effects.NAME_RE.match(plan["name"]):
        plan["name"] = "inspected_effect"
    return plan
