#!/usr/bin/env python3
"""Regenerate the tracked SYNTHETIC examples: level specs, plan maps and examples/library/assets.jsonl.

Positive examples are the shipped templates at default parameters. Negative examples are the same templates with deliberate
defects. Measured fields in the library come from the analysis, so the library cannot drift from the code.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from rbxlevel import project  # noqa: E402
from rbxlevel.core.style import load_style  # noqa: E402
from rbxlevel.domain import build, evaluate, mapview, spec as S  # noqa: E402
from rbxlevel.hooks import apply_mutations  # noqa: E402
from rbxlevel.tools import _template  # noqa: E402

P = project()
STYLE = load_style(P)
EX = P.root / "examples"
LIC = {"owner": "user", "spdx": "MIT", "notes": "Synthetic example generated by scripts/make_examples.py"}
(EX / "levels").mkdir(parents=True, exist_ok=True)


def entry(eid, title, tid, muts, polarity, desc, tags, level_type, traits, notes=None, rating=None):
    raw = apply_mutations(S.instantiate(_template(P, tid)), muts)
    raw["id"] = eid.replace("-", "_")
    spec_rel = f"examples/levels/{raw['id']}.json"
    (P.root / spec_rel).write_text(json.dumps(raw, indent=1, sort_keys=True) + "\n", encoding="utf-8")
    png_rel = f"examples/{'positive' if polarity == 'positive' else 'negative'}/{raw['id']}.png"
    norm, findings = S.prepare(raw, STYLE)
    mapview.render(norm, P.root / png_rel)
    res = evaluate.evaluate(raw, STYLE, P.root / "evals" / "rubric.yaml")
    m = res["metrics"]
    domain = {"level_type": level_type, "template": tid, "spec_file": spec_rel, "rooms": len(norm["rooms"]), "loops": int(m.get("loops", 0)),
              "teams": len({s.get("team") for s in norm["spawns"] if s.get("team")}),
              "footprint_studs": [norm["bounds"]["width"], norm["bounds"]["depth"]],
              "measurements": {k: m[k] for k in ("fairness_ratio", "longest_sightline", "landmark_visibility", "part_count") if k in m}}
    row = {"id": eid, "kind": "level", "title": title, "path": spec_rel, "preview": png_rel, "source_file": f"recipes/{tid}.yaml", "description": desc,
           "application": {"name": "Roblox Studio", "version": "unspecified (synthetic example)"}, "license": LIC,
           "provenance": {"origin": "synthetic-example", "creator": "rbxlevel example generator"}, "tags": tags,
           "style": {"traits": traits, "composition": f"{len(norm['rooms'])} rooms, {int(m.get('loops', 0))} loops"},
           "status": "curated", "polarity": polarity, "domain": domain}
    if rating is not None:
        row["rating"] = rating
    if notes:
        row["correction_notes"] = notes
    return row


rows = [
    entry("arena-two-team-loops-001", "Two-team loop arena", "loop_arena", [], "positive",
          "3x3 arena with an outer ring and four spokes into a central objective. Two independent routes per team, equal route lengths, staggered doors so no sightline spans the arena.",
          ["arena", "two-team", "loops", "symmetric", "objective"], "arena", ["several-routes", "fair", "short-sightlines"], rating=5),
    entry("hub-two-team-001", "Two-team hub and spoke", "hub_and_spoke", [], "positive",
          "Central hub with four spokes; teams spawn in opposite spokes and contest the hub. Staggered doors keep spawns out of each other's sight.",
          ["hub", "two-team", "objective", "readable"], "hub", ["single-route-per-team", "fair", "clear-landmark"], rating=4),
    entry("linear-raised-finale-001", "Linear with branches and a ramp finale", "linear_with_branches", [], "positive",
          "Zig-zag chain of rooms with two optional side rooms and a ramp up to the raised final room. Doors are staggered so you never see down the chain.",
          ["linear", "single-player", "ramp", "branches", "vertical"], "linear", ["staggered-doors", "optional-branches", "raised-finale"], rating=4),
    entry("hub-spawns-see-each-other", "Hub where spawns see each other (avoid)", "hub_and_spoke",
          [{"op": "unset", "target": "connection", "id": "c_west", "field": "at"}, {"op": "unset", "target": "connection", "id": "c_east", "field": "at"}],
          "negative", "AVOID: doors on the centre line let each team see the other's spawn straight through the hub.",
          ["hub", "spawn", "exposed", "sightline"], "hub", ["aligned-doors", "exposed-spawns"],
          notes=["sightlines: stagger the spawn-spoke doors off the centre line", "spawns: enemy spawns must not see each other"]),
    entry("arena-without-loops", "Arena with no loops (avoid)", "loop_arena",
          [{"op": "remove", "target": "connection", "id": i} for i in ("ring_02", "ring_03", "ring_04", "ring_06", "ring_07", "ring_08")],
          "negative", "AVOID: removing most of the ring leaves one route per team through a single room: no flanking, a choke point, a loop-less arena.",
          ["arena", "single-route", "chokepoint", "no-loops"], "arena", ["no-loops", "chokepoint"],
          notes=["routes: give arenas at least one loop and two independent routes", "pacing: avoid forcing every fight through one room"]),
    entry("hub-empty-dead-ends", "Hub with empty dead ends (avoid)", "hub_and_spoke",
          [{"op": "set", "target": "room", "id": "north", "field": "tags", "value": []}, {"op": "set", "target": "room", "id": "south", "field": "tags", "value": []}],
          "negative", "AVOID: north and south spokes are dead ends with nothing in them; players wander in and find nothing.",
          ["hub", "dead-end", "empty"], "hub", ["empty-dead-ends"], notes=["routes: tag dead ends loot/secret/safe or connect them"]),
]
rows.append({"id": "level-unreviewed-import", "kind": "level", "title": "Unreviewed level import", "path": "examples/levels/loop_arena.json" if False else "examples/levels/arena_two_team_loops_001.json",
             "license": {"owner": "unknown"}, "provenance": {"origin": "user-supplied"}, "tags": ["arena"], "status": "candidate", "polarity": "positive"})
out = EX / "library" / "assets.jsonl"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("\n".join(json.dumps(r, sort_keys=True) for r in rows) + "\n", encoding="utf-8")
print(f"wrote {len(rows)} entries")
