"""Skill export: turn what a repository has learned into a short agent skill (layer 5 of the learning layer).

:func:`export_skill` writes a skill folder for an agent client::

    <out>/<name>/SKILL.md                 frontmatter (name, description) + short guidance, points to the references
    <out>/<name>/references/parameters.md current parameter values with versions and which source won
    <out>/<name>/references/corrections.md the newest corrections for the chosen scope
    <out>/<name>/references/knowledge.md  promoted/learned items and the changelog tail

Scopes: ``global`` (only values and corrections promoted to global) or one project (project values, then global, then defaults).
The skill states the knowledge version it was generated from and the date. Regenerate it after promotions so the guidance stays in
step with what was learned. It is deliberately short (the SKILL.md is capped) and points at the repository's tools for detail.

Corrections come from ``feedback.recent_corrections`` unless the caller passes ``corrections=[{"decision", "request", "reason", "corrections": [{"dimension", "note"}], "at"}]``.
``dry_run=True`` (the default) returns the files' content without writing. Writing refuses to overwrite a SKILL.md that was not
generated by this function unless ``force=True``.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
from pathlib import Path
from typing import Any, Callable, Iterable

from . import __version__, agentfiles, feedback
from .mcpkit import ToolSpec, tool_catalog
from .params import ParamStore
from .project import Project
from .promote import KnowledgeStore
from .scope import Scope

MARKER = "<!-- generated by guide-core export_skill; regenerate instead of editing -->"
MAX_SKILL_LINES = 70


def _tool_rows(tools: Iterable[ToolSpec | dict]) -> list[dict]:
    rows = []
    for t in tools:
        if isinstance(t, ToolSpec):
            rows += tool_catalog([t])
        else:
            rows.append({"name": t["name"], "label": t.get("label", "read-only"), "group": t.get("group"), "line": t.get("line", "")})
    return rows


def export_skill(*, out_dir: str | Path, name: str, description: str, repo: str, repo_version: str = "", scope: Scope | None = None,
                 tools: Iterable[ToolSpec | dict] = (), workflow: Iterable[str] = (), verified: Iterable[str] = (), unverified: Iterable[str] = (),
                 params: ParamStore | None = None, knowledge: KnowledgeStore | None = None, project: Project | None = None,
                 corrections: list[dict] | None = None, max_corrections: int = 5, now: _dt.datetime | None = None, dry_run: bool = True,
                 force: bool = False) -> dict:
    scope = scope or Scope.make_global()
    now = now or _dt.datetime.now(_dt.timezone.utc)
    date = now.strftime("%Y-%m-%d")
    kversion = (params.knowledge_version() if params else 0) + (knowledge.version() if knowledge else 0)
    snap = params.snapshot(None if scope.is_global else scope) if params else {}
    changed = {n: s for n, s in snap.items() if s["source"] not in ("default",)}
    if corrections is None:  # repositories whose feedback rows carry no guide-core scope pass their own, already scoped, list
        corrections = feedback.recent_corrections(project, scope, max_corrections) if project is not None else []
    corrections = list(corrections)[:max_corrections]
    items = knowledge.retrievable(scope, now=now) if knowledge else []
    rows = _tool_rows(tools)

    lines = ["---", f"name: {name}", f"description: {json.dumps(description)}", "---", MARKER, f"# {repo}", "",
             f"Knowledge version {kversion} (parameters + changelog), generated {date} for scope **{scope.label}** from {repo} {repo_version}".rstrip() +
             f" with guide-core {__version__}. Regenerate after promotions.", "", "## When to use", description, ""]
    lines += ["## Tools (see the repository's tool list for arguments)"]
    lines += [f"- `{r['name']}` [{r['label']}{', ' + r['group'] if r['group'] else ''}]: {r['line']}" for r in rows[:25]]
    if len(rows) > 25:
        lines.append(f"- ... and {len(rows) - 25} more (`call` lists them)")
    wf = list(workflow)
    if wf:
        lines += ["", "## Workflow"] + [f"{i}. {w}" for i, w in enumerate(wf, 1)]
    ver, unver = list(verified), list(unverified)
    if ver or unver:
        lines += ["", "## Limits"] + [f"- Verified: {v}" for v in ver] + [f"- NOT verified: {u}" for u in unver]
    lines += ["", "## Current learned state"]
    lines.append(f"- {len(changed)} parameter(s) differ from the shipped default in this scope" + (": " + ", ".join(f"{n}={s['value']!r} (v{s['version']}, {s['source']})" for n, s in list(changed.items())[:6]) if changed else "")
                 + (" - details in references/parameters.md" if snap else ""))
    for c in corrections[:3]:
        note = "; ".join(f"{x['dimension']}: {x['note']}" for x in c["corrections"])[:140]
        lines.append(f"- Correction ({c['decision']}): {note}")
    if len(corrections) > 3 or items:
        lines.append(f"- {len(corrections)} correction(s) and {len(items)} learned item(s) in references/corrections.md and references/knowledge.md")
    if not (changed or corrections or items):
        lines.append("- Nothing learned yet for this scope: parameters are shipped defaults, no corrections recorded.")
    skill_md = "\n".join(lines) + "\n"

    p_lines = [f"# Parameters ({scope.label}, knowledge version {kversion}, {date})", "", "| name | value | source | version | default | range | locked |", "|---|---|---|---|---|---|---|"]
    for n, s in snap.items():
        spec = params.specs[n]  # type: ignore[union-attr]
        rng = f"{list(spec.choices)}" if spec.choices else f"{spec.min}..{spec.max} (step {spec.step:g})"
        p_lines.append(f"| {n} | {s['value']!r} | {s['source']} | {s['version'] if s['version'] is not None else '-'} | {s['default']!r} | {rng} | {'yes' if s['locked'] else 'no'} |")
    if not snap:
        p_lines.append("| (none registered) | | | | | | |")
    c_lines = [f"# Corrections ({scope.label})", ""]
    for c in corrections:
        c_lines.append(f"- {c['at'][:10]} {c['decision']}: {c['request']!r} - {c['reason']}" + "".join(f"\n  - {x['dimension']}: {x['note']}" for x in c["corrections"]))
    if not corrections:
        c_lines.append("- none recorded for this scope")
    k_lines = [f"# Learned items and changelog ({scope.label})", ""]
    k_lines += [f"- `{i['signature']}` (confidence {i['effective_confidence']}, scope {i['scope']}, confirmed in {len(i['confirmed_in'])} project(s)): {i['text']}" for i in items] or ["- no learned items"]
    k_lines += ["", "## Changelog (latest 15)", *(knowledge.render_changelog().splitlines()[-15:] if knowledge else ["- (no knowledge store)"])]
    files = {f"{name}/SKILL.md": skill_md, f"{name}/references/parameters.md": "\n".join(p_lines) + "\n",
             f"{name}/references/corrections.md": "\n".join(c_lines) + "\n", f"{name}/references/knowledge.md": "\n".join(k_lines) + "\n"}

    problems: list[str] = []
    if len(skill_md.splitlines()) > MAX_SKILL_LINES:
        problems.append(f"SKILL.md has {len(skill_md.splitlines())} lines (cap {MAX_SKILL_LINES}): shorten the tool list, workflow or limits")
    meta_ok = None
    try:
        meta, body = agentfiles.parse_frontmatter(skill_md)
        meta_ok = meta
    except ValueError as exc:
        problems.append(str(exc))
    if meta_ok is not None:
        if meta_ok.get("name") != name:
            problems.append("frontmatter name does not match")
        if not agentfiles.NAME_RE.match(name) or not 1 <= len(name) <= 64:
            problems.append(f"name '{name}' must be 1-64 chars of lowercase letters, digits and single hyphens")
        if not 1 <= len(description) <= 1024:
            problems.append("description must be 1-1024 characters")
    result: dict[str, Any] = {"dry_run": dry_run, "scope": scope.label, "knowledge_version": kversion, "date": date, "problems": problems,
                              "files": {k: (v if dry_run else f"{len(v)} chars") for k, v in files.items()}, "skill_lines": len(skill_md.splitlines())}
    if problems:
        result["written"] = []
        return result
    if dry_run:
        return result
    out = Path(out_dir)
    existing = out / name / "SKILL.md"
    if existing.exists() and MARKER not in existing.read_text(encoding="utf-8") and not force:
        raise ValueError(f"{existing} exists and was not generated by export_skill; pass force=True to replace it")
    written = []
    for rel, text in files.items():
        f = out / rel
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(text, encoding="utf-8")
        written.append(str(f))
    sk = agentfiles.validate_skill(out / name)
    if sk:
        result["problems"] = sk
    result["written"] = written
    return result


def brief(result: dict) -> dict:
    """Shrink an ``export_skill`` result for a tool answer: file names, the SKILL.md text (dry run) and the problems; not every reference file."""
    files = result.get("files", {})
    skill = next((v for k, v in files.items() if k.endswith("/SKILL.md") and result.get("dry_run")), None)
    out = {k: v for k, v in result.items() if k != "files"}
    out["files"] = sorted(files)
    if skill is not None:
        out["skill_md"] = skill
    return out


def add_export_skill_command(sub: Any, project: Project, kwargs_for: Callable[[Project, Scope], dict],
                             resolve: Callable[[Project, str, str | None], Scope] | None = None) -> None:
    """Register ``export-skill`` on a repository's CLI (``register_cli(sub, project)`` hook).

    ``kwargs_for(project, scope)`` returns the repository-specific arguments of :func:`export_skill` (name, description, repo, tools,
    workflow, verified/unverified lists, params, knowledge). Dry run by default; ``--write`` writes under ``--out``
    (default ``<workspace>/output/skills``). ``resolve(project, scope_name, place_id)`` turns ``--scope`` into a Scope; give one that checks the
    repository's registry so an unknown project is refused (the default accepts any name)."""
    p = sub.add_parser("export-skill", help="generate an agent skill from the current parameters, corrections and learned items (dry run unless --write)")
    p.add_argument("--scope", default="global", help="'global' or a project_id")
    p.add_argument("--place", help="place id (with a project scope)")
    p.add_argument("--out", help="output folder (default: <workspace>/output/skills)")
    p.add_argument("--write", action="store_true", help="write the files (default: show what would be written)")
    p.add_argument("--force", action="store_true", help="replace a SKILL.md that was not generated by export-skill")

    def handler(args: argparse.Namespace, pr: Project) -> int:
        sc = Scope.make_global() if args.scope == "global" else (resolve(pr, args.scope, args.place) if resolve else Scope(args.scope, args.place))
        kw = kwargs_for(pr, sc)
        res = export_skill(out_dir=args.out or (pr.output_dir / "skills"), scope=sc, project=pr, dry_run=not args.write, force=args.force, **kw)
        print(json.dumps(res, indent=2, ensure_ascii=False, default=str))
        return 1 if res["problems"] else 0

    p.set_defaults(handler=handler)
