"""Safe-fix planning and the Blender Python script generator.

Only findings whose rule is ``safe: true`` AND that carry a concrete ``fix_op`` are turned into operations. The script is emitted as
text for the hub (or a person) to run on a COPY of the .blend. It never edits an export file, saves, exports, imports modules other than
bpy/json, or touches the network. Names are embedded as JSON data, never spliced into code.
"""

from __future__ import annotations

import hashlib
import json

from .checks_rig_names import clean_name, sanitize_bone

SCRIPT_HEADER = '''\
"""Generated by asset-roblox-preflight (apply_safe_fix). REVIEW BEFORE RUNNING and run it on a COPY of the .blend.

It only renames objects/bones and applies scale/rotation on plain (unskinned) mesh objects, in that order of safety.
It does not save the file, export, upload or publish. After running: re-export, then run the preflight again.
"""
import json

import bpy
'''

SCRIPT_BODY = '''
RESULT = {"scale_applied": [], "rotation_applied": [], "bones_renamed": [], "objects_renamed": [], "skipped": []}


def _select_only(obj):
    for o in bpy.context.view_layer.objects:
        o.select_set(False)
    obj.select_set(True)
    bpy.context.view_layer.objects.active = obj


def _single_user(obj):
    if getattr(obj.data, "users", 1) > 1:
        obj.data = obj.data.copy()


def _apply(op, rotation=False, scale=False):
    obj = bpy.data.objects.get(op["object"])
    if obj is None:
        RESULT["skipped"].append({"op": op["op"], "object": op["object"], "why": "object not found in this .blend"})
        return
    if obj.type != "MESH":
        RESULT["skipped"].append({"op": op["op"], "object": op["object"], "why": "not a mesh object"})
        return
    _single_user(obj)
    _select_only(obj)
    bpy.ops.object.transform_apply(location=False, rotation=rotation, scale=scale)
    RESULT["rotation_applied" if rotation else "scale_applied"].append(op["object"])


def _unique(collection, wanted, current):
    name, n = wanted, 1
    while name in collection and name != current:
        n += 1
        name = "%s_%d" % (wanted, n)
    return name


def _find_bone(name):
    for arm in bpy.data.armatures:
        bone = arm.bones.get(name)
        if bone is not None:
            return arm, bone
    return None, None


for op in OPS:
    if op["op"] == "apply_scale":
        _apply(op, scale=True)
    elif op["op"] == "apply_rotation":
        _apply(op, rotation=True)

for op in OPS:
    if op["op"] == "rename_bone":
        arm, bone = _find_bone(op["bone"])
        if bone is None:
            RESULT["skipped"].append({"op": "rename_bone", "bone": op["bone"], "why": "bone not found in this .blend"})
            continue
        new = _unique(arm.bones, op["new"], op["bone"])
        bone.name = new
        RESULT["bones_renamed"].append([op["bone"], new])

for op in OPS:
    if op["op"] == "rename_object":
        obj = bpy.data.objects.get(op["old"])
        if obj is None:
            RESULT["skipped"].append({"op": "rename_object", "object": op["old"], "why": "object not found in this .blend"})
            continue
        new = _unique(bpy.data.objects, op["new"], op["old"])
        obj.name = new
        RESULT["objects_renamed"].append([op["old"], new])

print("PREFLIGHT_FIX_RESULT " + json.dumps(RESULT))
'''


def _unique_name(wanted: str, taken: set[str]) -> str:
    name, n = wanted, 1
    while name in taken:
        n += 1
        name = f"{wanted}_{n}"
    return name


def plan_operations(findings: list[dict], all_object_names: set[str], rules: list[str] | None = None) -> tuple[list[dict], list[dict]]:
    """Return (operations, skipped). Renames are merged per object so one object gets one final name."""
    ops: list[dict] = []
    skipped: list[dict] = []
    renames: dict[str, str] = {}
    taken = set(all_object_names)
    for f in findings:
        if not f.get("safe_fix") or not f.get("fix_op"):
            continue
        if rules and f["rule"] not in rules:
            continue
        op = f["fix_op"]
        kind = op["op"]
        if kind in ("apply_scale", "apply_rotation"):
            if op.get("kind") != "mesh":
                skipped.append({"rule": f["rule"], "object": op["object"], "why": "only mesh objects are changed; reset empties/armatures by hand after checking their children"})
            elif op.get("skinned"):
                skipped.append({"rule": f["rule"], "object": op["object"], "why": "skinned mesh: apply the transform on the armature and mesh together in Blender yourself"})
            elif not any(o.get("op") == kind and o.get("object") == op["object"] for o in ops):
                ops.append({"op": kind, "object": op["object"], "rule": f["rule"]})
        elif kind == "rename":
            renames.setdefault(op["object"], clean_name(op["object"]))
        elif kind == "rename_duplicates":
            bones = [o for o in op["occurrences"] if o["kind"] == "bone"]
            others = [o for o in op["occurrences"] if o["kind"] != "bone"]
            if len(bones) == 1 and others:
                new = _unique_name(op["name"] + "_bone", taken)
                taken.add(new)
                ops.append({"op": "rename_bone", "bone": op["name"], "new": new, "rule": f["rule"]})
            else:
                new = _unique_name(op["name"], taken)
                taken.add(new)
                skipped.append({"rule": f["rule"], "object": op["name"], "why": f"{len(op['occurrences'])} same-kind objects share this name and cannot be told apart by name; rename the extra copies by hand, e.g. '{new}'"})
        elif kind == "rename_bone":
            ops.append({"op": "rename_bone", "bone": op["bone"], "new": op["new"] or sanitize_bone(op["bone"]), "rule": f["rule"]})
    for old, new in renames.items():
        if new == old:
            continue
        taken.discard(old)
        final = _unique_name(new, taken)
        taken.add(final)
        ops.append({"op": "rename_object", "old": old, "new": final, "rule": "NAME_INVALID_CHARS/NAME_BLENDER_SUFFIX"})
    # one rename per bone: explicit (spin/root) beats computed names
    seen: dict[str, int] = {}
    uniq: list[dict] = []
    for op in ops:
        if op["op"] == "rename_bone":
            if op["bone"] in seen:
                continue
            seen[op["bone"]] = 1
        uniq.append(op)
    return uniq, skipped


def render_script(ops: list[dict]) -> str:
    payload = json.dumps(ops, sort_keys=True)
    return SCRIPT_HEADER + "\nOPS = json.loads(" + repr(payload) + ")\n" + SCRIPT_BODY


def script_id(script: str) -> str:
    return hashlib.sha256(script.encode("utf-8")).hexdigest()[:10]


FORBIDDEN_TOKENS = ("save_mainfile", "save_as_mainfile", "export_scene", "wm.save", "import os", "import sys", "subprocess", "urllib", "requests", "socket", "eval(", "exec(", "__import__", "open(")


def lint_script(script: str) -> list[str]:
    import ast

    code = "\n".join(line for line in script.splitlines() if not line.startswith("OPS = "))  # the OPS line is data (names), never code
    problems = [f"forbidden token '{t}'" for t in FORBIDDEN_TOKENS if t in code]
    try:
        tree = ast.parse(script)
    except SyntaxError as exc:
        return problems + [f"syntax error: {exc}"]
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for n in node.names:
                if n.name not in ("json", "bpy"):
                    problems.append(f"import of '{n.name}'")
        elif isinstance(node, ast.ImportFrom):
            problems.append(f"from-import of '{node.module}'")
    return problems
