#!/usr/bin/env python3
"""Regenerate the tracked SYNTHETIC examples: timeline sheets and examples/library/assets.jsonl.

Positive examples are the shipped recipes at chosen parameters. Negative examples are the same recipes with
deliberate defects (applied with hooks.apply_mutations). Measured fields in the library come from the analysis,
so the library cannot drift from the code. These are demonstrations of the format, not production assets.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from rbxvfx import project  # noqa: E402
from rbxvfx.core.style import load_style  # noqa: E402
from rbxvfx.domain import analysis, effects, preview  # noqa: E402
from rbxvfx.hooks import apply_mutations  # noqa: E402

P = project()
STYLE = load_style(P)
EX = P.root / "examples"
LIC = {"owner": "user", "spdx": "MIT", "notes": "Synthetic example generated by scripts/make_examples.py"}
PAL = {"arcane_burst": ["#8c5cff", "#33ccff"], "ember_aura": ["#ff8c26", "#8c1f14"],
       "energy_beam": ["#e6ffff", "#33b3ff"], "sprint_trail": ["#4de6ff", "#3359ff"]}


def recipe(rid):
    return effects.load_recipe(P.root / "recipes" / f"{rid}.yaml")


def entry(eid, title, rid, rel_png, plan, polarity, description, tags, traits, notes=None, rating=None, kind=None):
    res = analysis.analyze(plan, STYLE, "mobile")
    m = res["metrics"]
    domain = {"effect_kind": kind or plan["kind"], "recipe": rid, "particles_peak": m["particles_peak"],
              "intended_distance_studs": 30, "platforms": ["mobile", "desktop"] if res["findings"] == [] else ["desktop"],
              "theme": tags[:2]}
    if "duration_seconds" in m:
        domain["duration_seconds"] = m["duration_seconds"]
    row = {"id": eid, "kind": "effect", "title": title, "path": f"examples/{rel_png}", "preview": f"examples/{rel_png}",
           "source_file": f"recipes/{rid}.yaml", "description": description,
           "application": {"name": "Roblox Studio", "version": "unspecified (synthetic example)"}, "license": LIC,
           "provenance": {"origin": "synthetic-example", "creator": "rbxvfx example generator"}, "tags": tags,
           "style": {"traits": traits, "palette": PAL[rid]}, "status": "curated", "polarity": polarity, "domain": domain}
    if rating is not None:
        row["rating"] = rating
    if notes:
        row["correction_notes"] = notes
    return row


rows = []
# --- positive -------------------------------------------------------------------------------------
specs = [
    ("arcane-burst-purple-001", "Arcane burst (purple)", "arcane_burst", {}, "positive/arcane_burst.png",
     "One-shot magical burst: fast sparks plus a soft central flash; fades fully, readable at mid distance.",
     ["burst", "magic", "arcane", "purple", "one-shot"], ["fast-attack", "full-fade", "additive-glow", "two-layer"], 5),
    ("ember-aura-warm-001", "Ember aura (warm)", "ember_aura", {}, "positive/ember_aura.png",
     "Looping rising embers with soft haze and a warm point light; steady and cheap.",
     ["aura", "fire", "ember", "loop", "warm"], ["steady-state", "soft-haze", "warm-light"], 4),
    ("energy-beam-cyan-001", "Energy beam (cyan)", "energy_beam", {}, "positive/energy_beam.png",
     "Glowing cyan beam with a gentle curve and impact sparks; 12 segments.",
     ["beam", "energy", "cyan", "sci-fi"], ["clean-beam", "impact-accent"], 4),
    ("sprint-trail-blue-001", "Sprint trail (blue)", "sprint_trail", {}, "positive/sprint_trail.png",
     "Narrowing blue ribbon trail that fades out; needs motion to show.",
     ["trail", "speed", "blue", "movement"], ["tapered-ribbon", "full-fade"], 4),
]
for eid, title, rid, params, png, desc, tags, traits, rating in specs:
    plan = effects.build_plan(recipe(rid), params, name=rid)
    preview.render_timeline(plan, EX / png)
    rows.append(entry(eid, title, rid, png, plan, "positive", desc, tags, traits, rating=rating))

# --- negative ---------------------------------------------------------------------------------------
bad = [
    ("burst-too-heavy", "Burst, far too many particles (avoid)", "arcane_burst",
     [{"op": "set_emit", "instance": "sparks", "value": 400}], "negative/burst_too_heavy.png",
     "AVOID: 400 sparks in one burst blows the mobile budget and floods the screen. Fewer, larger, better-shaped sparks read better.",
     ["burst", "magic", "performance", "too-many-particles"], ["overdraw"],
     ["density: far fewer sparks; shape them with size and speed instead", "performance: stay under the platform particle budget"]),
    ("aura-pops-out", "Aura that pops out (avoid)", "ember_aura",
     [{"op": "set_property", "instance": "embers", "property": "Transparency", "value": {"sequence": [[0, 1], [0.2, 0.1], [1, 0.1]]}},
      {"op": "set_property", "instance": "embers", "property": "Size", "value": {"sequence": [[0, 0.3], [1, 0.3]]}}],
     "negative/aura_pops_out.png",
     "AVOID: embers stay fully visible until they vanish: a visible pop at the end of every particle's life.",
     ["aura", "fire", "ember", "popping"], ["abrupt-end"],
     ["timing: fade transparency to ~1 and shrink to 0 at the end of life"]),
    ("burst-too-small", "Burst, unreadably small (avoid)", "arcane_burst",
     [{"op": "set_property", "instance": "sparks", "property": "Size", "value": {"sequence": [[0, 0], [0.5, 0.08], [1, 0]]}},
      {"op": "set_property", "instance": "flash", "property": "Size", "value": {"sequence": [[0, 0], [0.5, 0.15], [1, 0]]}}],
     "negative/burst_too_small.png",
     "AVOID: nothing larger than ~0.15 studs: invisible at gameplay distance (largest element < 0.8% of screen height).",
     ["burst", "magic", "readability", "too-small"], ["tiny"],
     ["size: raise the peak size so the largest element is at least ~0.8% of screen height at 30 studs"]),
]
for eid, title, rid, muts, png, desc, tags, traits, notes in bad:
    plan = effects.build_plan(apply_mutations(recipe(rid), muts), name=rid)
    preview.render_timeline(plan, EX / png)
    rows.append(entry(eid, title, rid, png, plan, "negative", desc, tags, traits, notes=notes, rating=1))

# --- an uncurated candidate (never returned by default) -------------------------------------------------
rows.append({"id": "burst-unreviewed-import", "kind": "effect", "title": "Unreviewed burst import", "path": "examples/positive/arcane_burst.png",
             "license": {"owner": "unknown"}, "provenance": {"origin": "user-supplied"}, "tags": ["burst"],
             "status": "candidate", "polarity": "positive"})

out = EX / "library" / "assets.jsonl"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("\n".join(json.dumps(r, sort_keys=True) for r in rows) + "\n", encoding="utf-8")
print(f"wrote {len(rows)} entries and previews under {EX}")
