#!/usr/bin/env python3
"""Regenerate the tracked SYNTHETIC examples: small PNGs with known properties (examples/shared and one folder per demo project), the example profile, the
library manifest (examples/library/assets.jsonl) and examples/README.md. Use --check to verify the tracked files are up to date (compares decoded pixels, not PNG
bytes, so a different Pillow version does not matter). Every image comes from visualverify/evalgen.py with the parameters listed here: nothing is a real render.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from visualverify import evalgen as G  # noqa: E402

G_BG, G_FG = [200, 200, 200], [30, 30, 30]
SHARED = {  # path under examples/ -> (spec, expected facts a measurement must reproduce, tags)
    "shared/ref_hero.png": ({"gen": "rect", "size": [128, 128], "bg": G_BG, "fg": G_FG, "box": [32, 32, 96, 96]}, {"fill": 0.25}, ["silhouette", "reference"]),
    "shared/cand_close.png": ({"gen": "rect", "size": [128, 128], "bg": G_BG, "fg": G_FG, "box": [34, 32, 98, 96]}, {"iou_vs_ref_hero": 0.939394}, ["silhouette", "known-good"]),
    "shared/cand_shifted.png": ({"gen": "rect", "size": [128, 128], "bg": G_BG, "fg": G_FG, "box": [48, 32, 112, 96]}, {"iou_vs_ref_hero": 0.6}, ["silhouette", "known-bad"]),
    "shared/tile_seamless.png": ({"gen": "smooth_tile", "size": [128, 128], "seed": 7, "sigma": 0.03}, {"seam_ratio_max": 1.5}, ["tiling", "known-good"]),
    "shared/tile_seamed.png": ({"gen": "smooth_crop", "size": [128, 128], "seed": 7, "sigma": 0.03}, {"seam_ratio_min": 4.0}, ["tiling", "known-bad"]),
    "shared/tile_lattice.png": ({"gen": "lattice", "size": [128, 128], "period": 32, "radius": 2}, {"repeat_lag_px": [32, 0]}, ["tiling", "known-bad"]),
    "shared/albedo_mid_gray.png": ({"gen": "solid", "size": [64, 64], "color": [128, 128, 128]}, {"out_of_range_fraction": 0.0}, ["pbr", "known-good"]),
    "shared/albedo_too_dark.png": ({"gen": "solid", "size": [64, 64], "color": [10, 10, 10]}, {"out_of_range_fraction": 1.0}, ["pbr", "known-bad"]),
    "shared/roughness_varied.png": ({"gen": "gray_noise", "size": [64, 64], "seed": 3, "mean": 0.5, "amp": 0.2}, {"gray_spread": 0.0}, ["pbr", "known-good"]),
    "shared/roughness_black.png": ({"gen": "solid", "size": [64, 64], "color": [0, 0, 0]}, {"std": 0.0}, ["pbr", "known-bad"]),
    "shared/metalness_binary.png": ({"gen": "checker", "size": [64, 64], "cell": 16, "a": [0, 0, 0], "b": [255, 255, 255]}, {"mid_fraction": 0.0}, ["pbr", "known-good"]),
    "shared/metalness_gradient.png": ({"gen": "hgradient", "size": [256, 8]}, {"mid_fraction": 0.796875}, ["pbr", "known-bad"]),
    "shared/normal_valid.png": ({"gen": "normal_noisy", "size": [64, 64], "seed": 5, "tilt": 0.3}, {"bad_length_fraction": 0.0}, ["pbr", "known-good"]),
    "shared/normal_not_a_normal_map.png": ({"gen": "solid", "size": [64, 64], "color": [200, 100, 50]}, {"mean_length": 0.85984}, ["pbr", "known-bad"]),
    "shared/palette_halves.png": ({"gen": "bands", "size": [64, 64], "colors": [[200, 30, 30], [30, 30, 200]], "axis": "x"}, {"dominant": ["#1e1ec8", "#c81e1e"]}, ["palette"]),
    "shared/diff_before.png": ({"gen": "solid", "size": [100, 100], "color": [100, 100, 100]}, {}, ["diff"]),
    "shared/diff_after.png": ({"gen": "boxed", "base": {"gen": "solid", "size": [100, 100], "color": [100, 100, 100]}, "box": [10, 10, 30, 30], "color": [200, 200, 200]}, {"changed_fraction": 0.04}, ["diff"]),
}
PER_PROJECT = {
    "demo-pixel-brawler/ref_sprite.png": ({"gen": "checker", "size": [64, 64], "cell": 8, "a": [40, 40, 90], "b": [220, 200, 60]}, {}, ["pixel-art", "reference"]),
    "demo-realistic-tycoon/ref_factory.png": ({"gen": "smooth_tile", "size": [96, 96], "seed": 21, "sigma": 0.04, "tint": [0.9, 0.85, 0.8]}, {}, ["realistic", "reference"]),
    "demo-stylized-obby/ref_stage.png": ({"gen": "bands", "size": [96, 96], "colors": [[240, 240, 220], [200, 30, 30], [30, 150, 30]], "axis": "x"}, {}, ["stylized", "reference"]),
}
PROFILE = {"schema": "visualverify-profile/1", "name": "demo-obby-look", "description": "SYNTHETIC example profile built from examples/demo-stylized-obby/ref_stage.png (numbers only)",
           "source": {"image": "ref_stage.png", "size": [96, 96]}, "palette": [{"hex": "#f0f0dc", "share": 0.3333}, {"hex": "#c81e1e", "share": 0.3333}, {"hex": "#1e961e", "share": 0.3333}],
           "ranges": {"saturation_mean": [0.45, 0.75], "value_mean": [0.65, 0.95], "luminance_mean": [0.35, 0.75], "contrast_min": 0.4, "edge_density": [0.0, 0.1]}}
LIC = {"owner": "user", "spdx": "MIT", "notes": "Synthetic example generated by scripts/make_examples.py"}
README = """# Examples (all SYNTHETIC)

Every image here is generated by `scripts/make_examples.py` from `visualverify/evalgen.py` with the parameters in the script: flat shapes, gradients, seeded noise.
**None of them is a real render, screenshot or texture.** They exist so the tools can be tried and so the manifest has entries with known properties.

- `shared/`: readable by every project (the knowns: matching and shifted silhouettes, a seamless and a seamed tile, in-range and out-of-range PBR maps, a two-colour palette, a before/after pair).
- `demo-pixel-brawler/`, `demo-realistic-tycoon/`, `demo-stylized-obby/`: one reference each; only that project's tools may read its folder (see `projects.yaml`, `image_roots`).
- `profiles/demo-obby-look.json`: the shape of a saved target profile (numbers only).
- `library/assets.jsonl`: manifest entries (`reference_image`, `measurement_case`, `target_profile`) with the numbers a correct measurement must reproduce; `tests/` checks them against the code.

Try: `python -m visualverify iou examples/shared/cand_shifted.png examples/shared/ref_hero.png --project-id demo-stylized-obby` (IoU 0.6, hand-computed in the manifest).
"""


def render() -> dict[str, bytes | np.ndarray]:
    out: dict = {}
    for rel, (spec, _, _) in {**SHARED, **PER_PROJECT}.items():
        out[f"examples/{rel}"] = G.build(spec)
    return out


def manifest() -> list[dict]:
    rows = []
    for rel, (spec, expected, tags) in {**SHARED, **PER_PROJECT}.items():
        is_case = bool(expected)
        arr = G.build(spec)
        name = Path(rel).stem
        row = {"id": ("case-" if is_case else "ref-") + name.replace("_", "-"), "kind": "measurement_case" if is_case else "reference_image", "title": name, "path": f"examples/{rel}",
               "description": ("Synthetic image with known properties: " + json.dumps(expected, sort_keys=True)) if is_case else "Synthetic reference image (flat or seeded-noise, not a real render)",
               "license": LIC, "status": "curated", "polarity": "negative" if "known-bad" in tags else "positive", "tags": sorted(set(tags + ["synthetic"])),
               "provenance": {"creator": "visualverify example generator", "origin": "synthetic-example"},
               "domain": {"image_kind": "tile" if "tiling" in tags else ("pbr_map" if "pbr" in tags else "render"), "size": [int(arr.shape[1]), int(arr.shape[0])], "generator": spec}}
        if is_case:
            row["domain"]["expected"] = expected
        if "known-bad" in tags:
            row["correction_notes"] = ["a measurement should flag this image (see domain.expected)"]
        rows.append(row)
    rows.append({"id": "profile-demo-obby-look", "kind": "target_profile", "title": "demo-obby-look", "path": "examples/profiles/demo-obby-look.json",
                 "description": "Synthetic target profile (numbers only) in the format save_target_profile writes", "license": LIC, "status": "curated", "polarity": "positive",
                 "tags": ["profile", "synthetic"], "provenance": {"creator": "visualverify example generator", "origin": "synthetic-example"}, "domain": {"profile": "demo-obby-look"}})
    return rows


def files() -> dict[str, str]:
    return {"examples/profiles/demo-obby-look.json": json.dumps(PROFILE, indent=2, sort_keys=True) + "\n", "examples/README.md": README,
            "examples/library/assets.jsonl": "".join(json.dumps(r, sort_keys=True, ensure_ascii=False) + "\n" for r in manifest())}


def main() -> int:
    check = "--check" in sys.argv
    bad = []
    for rel, arr in render().items():
        f = ROOT / rel
        if check:
            if not f.exists() or not np.array_equal(np.asarray(Image.open(f)), arr):
                bad.append(rel)
        else:
            f.parent.mkdir(parents=True, exist_ok=True)
            Image.fromarray(arr, "RGBA" if arr.shape[-1] == 4 else "RGB").save(f, format="PNG", compress_level=6, optimize=False)
    for rel, text in files().items():
        f = ROOT / rel
        if check:
            if not f.exists() or f.read_text(encoding="utf-8") != text:
                bad.append(rel)
        else:
            f.parent.mkdir(parents=True, exist_ok=True)
            f.write_text(text, encoding="utf-8")
    if check:
        print("out of date: " + ", ".join(bad) if bad else "examples are current")
        return 1 if bad else 0
    print("wrote examples")
    return 0


if __name__ == "__main__":
    sys.exit(main())
