"""Agent Skills validation and cross-client instruction-file sync.

``AGENTS.md`` and ``skills/<name>/SKILL.md`` are the canonical sources. Other
clients look in different places, so ``sync`` writes *copies* (not symlinks,
which are unreliable on Windows) and ``--check`` fails if any copy drifted.

This module does not know which client reads which file; the README keeps that
table and marks it as "documented by the client vendor, verify for your version".
"""

from __future__ import annotations

import hashlib
import re
import shutil
from pathlib import Path

import yaml

NAME_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
GENERATED = "<!-- GENERATED by scripts/sync_agent_files.py from AGENTS.md. Edit AGENTS.md, then re-run the script. -->\n\n"
CLIENT_FILES = ("CLAUDE.md", "GEMINI.md", ".github/copilot-instructions.md")
SKILL_MIRRORS = (".claude/skills", ".agents/skills", ".github/skills")


def parse_frontmatter(text: str) -> tuple[dict, str]:
    if not text.startswith("---"):
        raise ValueError("SKILL.md must start with YAML frontmatter ('---')")
    parts = text.split("---", 2)
    if len(parts) < 3:
        raise ValueError("SKILL.md frontmatter is not closed with '---'")
    data = yaml.safe_load(parts[1]) or {}
    if not isinstance(data, dict):
        raise ValueError("frontmatter must be a mapping")
    return data, parts[2]


def validate_skill(skill_dir: Path) -> list[str]:
    """Validate against the Agent Skills specification (name, description, optional fields)."""
    problems = []
    f = Path(skill_dir) / "SKILL.md"
    if not f.exists():
        return [f"{skill_dir}: missing SKILL.md"]
    try:
        meta, body = parse_frontmatter(f.read_text(encoding="utf-8"))
    except ValueError as exc:
        return [f"{f}: {exc}"]
    name = meta.get("name")
    if not isinstance(name, str) or not 1 <= len(name) <= 64 or not NAME_RE.match(name):
        problems.append(f"{f}: 'name' must be 1-64 chars of lowercase letters, digits and single hyphens")
    elif name != Path(skill_dir).name:
        problems.append(f"{f}: 'name' ({name}) must match the directory name ({Path(skill_dir).name})")
    desc = meta.get("description")
    if not isinstance(desc, str) or not 1 <= len(desc) <= 1024:
        problems.append(f"{f}: 'description' must be 1-1024 characters")
    comp = meta.get("compatibility")
    if comp is not None and (not isinstance(comp, str) or not 1 <= len(comp) <= 500):
        problems.append(f"{f}: 'compatibility' must be 1-500 characters")
    md = meta.get("metadata")
    if md is not None and (not isinstance(md, dict) or not all(isinstance(v, str) for v in md.values())):
        problems.append(f"{f}: 'metadata' must map strings to strings")
    if not body.strip():
        problems.append(f"{f}: skill body is empty")
    if len(body.splitlines()) > 500:
        problems.append(f"{f}: body is over 500 lines; move detail into references/ (progressive disclosure)")
    return problems


def validate_all_skills(root: Path) -> list[str]:
    skills = Path(root) / "skills"
    if not skills.is_dir():
        return [f"{skills}: no skills directory"]
    dirs = [d for d in sorted(skills.iterdir()) if d.is_dir()]
    if not dirs:
        return [f"{skills}: no skills found"]
    return [p for d in dirs for p in validate_skill(d)]


def _tree_hash(path: Path) -> str:
    h = hashlib.sha256()
    for f in sorted(p for p in Path(path).rglob("*") if p.is_file() and "__pycache__" not in p.parts):
        h.update(str(f.relative_to(path)).encode())
        h.update(f.read_bytes())
    return h.hexdigest()


def sync(root: Path, check: bool = False) -> list[str]:
    """Write (or with ``check`` only verify) client instruction files and skill mirrors.

    Returns a list of human-readable differences; empty means everything is in sync.
    """
    root = Path(root)
    diffs: list[str] = []
    agents = root / "AGENTS.md"
    if not agents.exists():
        return ["AGENTS.md is missing"]
    body = GENERATED + agents.read_text(encoding="utf-8")
    for rel in CLIENT_FILES:
        target = root / rel
        if not target.exists() or target.read_text(encoding="utf-8") != body:
            diffs.append(f"{rel} is {'missing' if not target.exists() else 'out of date'}")
            if not check:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(body, encoding="utf-8")
    skills = root / "skills"
    for skill in sorted(d for d in skills.iterdir() if d.is_dir()) if skills.is_dir() else []:
        for mirror in SKILL_MIRRORS:
            target = root / mirror / skill.name
            if not target.exists() or _tree_hash(target) != _tree_hash(skill):
                diffs.append(f"{mirror}/{skill.name} is {'missing' if not target.exists() else 'out of date'}")
                if not check:
                    if target.exists():
                        shutil.rmtree(target)
                    shutil.copytree(skill, target, ignore=shutil.ignore_patterns("__pycache__"))
    return diffs
